import 'server-only'
import {getDb,ensureSchema} from './client'
import {decryptSecret,encryptSecret} from '@/lib/secrets'
export type LeadStatus='NEW'|'APPROVED'|'REJECTED'|'ROUTED'
export type SurgeryLead={id:string;user_id:string|null;name:string;phone:string;city:string;procedure:string;notes:string;status:LeadStatus;reviewed_by:string|null;reviewed_at:string|null;reject_reason:string|null;created_at:string}
export type Referral={id:string;lead_id:string;kind:'doctor'|'diagnostic';doctor_id:string|null;centre_name:string|null;status:string;created_at:string}
async function db(){await ensureSchema();return getDb()}
export function decodeEnquiryNotes(id:string,notes:string){return notes.startsWith('v2:')||notes.startsWith('v1:')?decryptSecret(notes,'enquiry:'+id):notes}
const decode=(r:SurgeryLead)=>({...r,notes:decodeEnquiryNotes(r.id,r.notes)})
export async function createLead(input:{id:string;userId?:string|null;name:string;phone:string;city?:string;procedure?:string;notes?:string}){await(await db()).query('INSERT INTO clinic.surgery_leads(id,user_id,name,phone,city,procedure,notes) VALUES($1,$2,$3,$4,$5,$6,$7)',[input.id,input.userId??null,input.name,input.phone,input.city??'',input.procedure??'',encryptSecret(input.notes??'','enquiry:'+input.id)])}
export async function listLeadsWithEstimateFlag(){const rows=await(await db()).query<SurgeryLead&{has_estimate:boolean}>(`SELECT l.*,EXISTS(SELECT 1 FROM clinic.estimates e WHERE e.lead_id=l.id) has_estimate FROM clinic.surgery_leads l ORDER BY created_at DESC LIMIT 500`);return rows.map(r=>({...decode(r),has_estimate:r.has_estimate}))}
export async function listLeads(status?:LeadStatus){const rows=await(await db()).query<SurgeryLead>('SELECT * FROM clinic.surgery_leads WHERE ($1::text IS NULL OR status=$1) ORDER BY created_at DESC LIMIT 500',[status??null]);return rows.map(decode)}
export async function getLead(id:string){const row=await(await db()).one<SurgeryLead>('SELECT * FROM clinic.surgery_leads WHERE id=$1',[id]);return row?decode(row):undefined}
export async function transitionLead(input:{id:string;from:LeadStatus;to:LeadStatus;adminId:string;reason?:string|null}){return(await db()).transaction(async tx=>{const moved=await tx.one('UPDATE clinic.surgery_leads SET status=$3,reviewed_by=$4,reviewed_at=now(),reject_reason=$5 WHERE id=$1 AND status=$2 RETURNING id',[input.id,input.from,input.to,input.adminId,input.reason??null]);if(moved)await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'enquiry:review',$2)",[input.adminId,input.id]);return Boolean(moved)})}
export async function addReferral(input:{id:string;leadId:string;kind:'doctor'|'diagnostic';doctorId?:string|null;centreName?:string|null}){await(await db()).query("INSERT INTO clinic.referrals(id,lead_id,kind,doctor_id,centre_name,status) VALUES($1,$2,$3,$4,$5,'RECORDED')",[input.id,input.leadId,input.kind,input.doctorId??null,input.centreName??null])}
export async function listReferrals(leadId:string){return(await db()).query<Referral>('SELECT * FROM clinic.referrals WHERE lead_id=$1 ORDER BY created_at',[leadId])}
export async function referralsForDoctor(doctorId:string){const rows=await(await db()).query<Referral&{lead_name:string;lead_phone:string;procedure:string;city:string;notes:string}>(`SELECT r.*,l.name lead_name,l.phone lead_phone,l.procedure,l.city,l.notes FROM clinic.referrals r JOIN clinic.surgery_leads l ON l.id=r.lead_id WHERE r.doctor_id=$1 ORDER BY r.created_at DESC LIMIT 200`,[doctorId]);return rows.map(r=>({...r,notes:decodeEnquiryNotes(r.lead_id,r.notes)}))}
export async function leadsForUser(userId:string){const rows=await(await db()).query<SurgeryLead>('SELECT * FROM clinic.surgery_leads WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200',[userId]);return rows.map(decode)}
