import 'server-only'
import {randomUUID} from 'node:crypto'
import {getDb,ensureSchema,type Db} from './client'
export type DomainEvent={id:string;kind:string;subject_id:string|null;payload:Record<string,unknown>;payload_version:number;status:'PENDING'|'SENT'|'FAILED';attempts:number;lease_token:string|null;last_error:string|null;available_at:string;created_at:string}
export const MAX_ATTEMPTS=5,CLAIM_MINUTES=1
async function db(){await ensureSchema();return getDb()}
export async function emit(input:{kind:string;subjectId?:string|null;payload?:Record<string,unknown>;eventKey?:string},transaction?:Db):Promise<void>{const d=transaction??await db();await d.query('INSERT INTO domain_events(kind,subject_id,payload,event_key) VALUES($1,$2,$3::jsonb,$4) ON CONFLICT DO NOTHING',[input.kind,input.subjectId??null,JSON.stringify(input.payload??{}),input.eventKey??null])}
export async function claimBatch(limit=20):Promise<DomainEvent[]>{const rows=await(await db()).query<DomainEvent>(`UPDATE domain_events SET locked_until=now()+interval '60 seconds',lease_token=$2,attempts=attempts+1
 WHERE id IN(SELECT id FROM domain_events WHERE status='PENDING' AND available_at<=now() AND (locked_until IS NULL OR locked_until<now()) ORDER BY available_at,id LIMIT $1 FOR UPDATE SKIP LOCKED) RETURNING *`,[Math.min(50,Math.max(1,limit)),randomUUID()]);return rows.map(r=>({...r,id:String(r.id),attempts:Number(r.attempts),payload:typeof r.payload==='string'?JSON.parse(r.payload):r.payload}))}
export async function markSent(id:string|number,leaseToken?:string){if(!leaseToken)throw new Error('Worker lease token required');const row=await(await db()).one("UPDATE domain_events SET status='SENT',locked_until=NULL,lease_token=NULL,last_error=NULL WHERE id=$1 AND lease_token=$2 AND locked_until>now() AND status='PENDING' RETURNING id",[String(id),leaseToken]);if(!row)throw new Error('Worker lease lost')}
export async function markFailed(id:string|number,attempts:number,error:string,leaseToken?:string,permanent=false){if(!leaseToken)throw new Error('Worker lease token required');const delay=Math.min(900,5*2**Math.min(attempts,10))+Math.floor(Math.random()*5);await(await db()).query(`UPDATE domain_events SET status=$3,locked_until=NULL,lease_token=NULL,last_error=$4,available_at=now()+($5||' seconds')::interval WHERE id=$1 AND lease_token=$2 AND locked_until>clock_timestamp() AND status='PENDING'`,[String(id),leaseToken,permanent||attempts>=MAX_ATTEMPTS?'FAILED':'PENDING',error.slice(0,150),String(delay)])}
export async function deadLetters(limit=50){return(await db()).query<DomainEvent>("SELECT * FROM domain_events WHERE status='FAILED' ORDER BY created_at DESC LIMIT $1",[limit])}
export async function pendingCount(){const row=await(await db()).one<{n:string}>("SELECT count(*) n FROM domain_events WHERE status='PENDING'");return Number(row?.n??0)}
