import * as SQLite from 'expo-sqlite'
import * as SecureStore from 'expo-secure-store'
import * as Crypto from 'expo-crypto'
type Session={token:string;userId:string;deviceId:string;expiresAt:string;origin:string;offlineEnabled?:boolean}
export type Intent={key:string;kind:'BOOK'|'CANCEL';payload:Record<string,unknown>}
let database:SQLite.SQLiteDatabase|null=null
const options={keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY}
export async function session():Promise<Session|null>{const saved=await SecureStore.getItemAsync('carenest.session',options);if(!saved)return null;const s=JSON.parse(saved) as Session;if(new Date(s.expiresAt).getTime()<=Date.now()){await logout();return null}return s}
export async function setSession(s:Session){await logout();await SecureStore.setItemAsync('carenest.session',JSON.stringify(s),options)}
export async function setOfflineRecords(enabled:boolean){const s=await session();if(!s)throw new Error('Pair this device first.');await SecureStore.setItemAsync('carenest.session',JSON.stringify({...s,offlineEnabled:enabled}),options);if(!enabled&&database)await database.execAsync('DELETE FROM snapshot')}
export async function cacheSnapshot(value:Record<string,unknown>){const s=await session();if(!s?.offlineEnabled)return;if(value.userId!==s.userId)throw new Error('The snapshot belongs to a different account.');const d=await db(),observed=new Date(String(value.serverTime)).getTime();if(!Number.isFinite(observed)||Math.abs(observed-Date.now())>300000)throw new Error('Correct the device clock before enabling offline records.');await d.runAsync('INSERT OR REPLACE INTO snapshot(id,user_id,body,observed_at,expires_at) VALUES(1,?,?,?,?)',s.userId,JSON.stringify(value),observed,Math.min(observed+24*3600000,new Date(s.expiresAt).getTime()))}
export async function cachedSnapshot():Promise<Record<string,unknown>|null>{const s=await session();if(!s?.offlineEnabled)return null;const d=await db(),value=await d.getFirstAsync<{user_id:string;body:string;observed_at:number;expires_at:number}>('SELECT * FROM snapshot WHERE id=1');if(!value)return null;if(value.user_id!==s.userId||value.expires_at<=Date.now()||Date.now()<value.observed_at-300000){await d.execAsync('DELETE FROM snapshot');return null}return JSON.parse(value.body)}
async function db(){const s=await session();if(!s)throw new Error('Pair your own device first.');if(database)return database;let key=await SecureStore.getItemAsync('carenest.queue-key',options);if(!key){key=Array.from(Crypto.getRandomBytes(32),b=>b.toString(16).padStart(2,'0')).join('');await SecureStore.setItemAsync('carenest.queue-key',key,options)}if(!/^[a-f0-9]{64}$/.test(key))throw new Error('Invalid device storage key.');const next=await SQLite.openDatabaseAsync('carenest-intents.db');try{await next.execAsync(`PRAGMA key = "x'${key}'"`);const cipher=await next.getFirstAsync<Record<string,string>>('PRAGMA cipher_version');if(!cipher||!Object.values(cipher).some(Boolean))throw new Error('Use a SQLCipher native development build. Expo Go cannot store this offline queue securely.');await next.execAsync('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS intents(key TEXT PRIMARY KEY,kind TEXT NOT NULL,payload TEXT NOT NULL,created_at INTEGER NOT NULL,error TEXT); CREATE TABLE IF NOT EXISTS snapshot(id INTEGER PRIMARY KEY CHECK(id=1),user_id TEXT NOT NULL,body TEXT NOT NULL,observed_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);');database=next;return next}catch(e){await next.closeAsync();throw e}}
export async function enqueue(intent:Intent){const d=await db(),n=await d.getFirstAsync<{n:number}>('SELECT count(*) n FROM intents');if((n?.n??0)>=20)throw new Error('Review your pending requests before adding more.');await d.runAsync('INSERT INTO intents(key,kind,payload,created_at) VALUES(?,?,?,?)',intent.key,intent.kind,JSON.stringify(intent.payload),Date.now())}
export async function queue(){const d=await db();await d.runAsync('DELETE FROM intents WHERE created_at<?',Date.now()-24*3600000);return d.getAllAsync<{key:string;kind:'BOOK'|'CANCEL';payload:string;error:string|null}>('SELECT * FROM intents ORDER BY created_at,key')}
export async function settle(key:string,error?:string){const d=await db();if(error)await d.runAsync('UPDATE intents SET error=? WHERE key=?',error,key);else await d.runAsync('DELETE FROM intents WHERE key=?',key)}
export async function logout(){if(database){await database.closeAsync();database=null}await SQLite.deleteDatabaseAsync('carenest-intents.db').catch(()=>{});await SecureStore.deleteItemAsync('carenest.queue-key',options);await SecureStore.deleteItemAsync('carenest.session',options)}
