'use server'
import {requireUser,currentAdmin} from '@/lib/auth'
import {revalidatePath} from 'next/cache'
import {DomainError} from '@/lib/domain/errors'
import {saveCompanySettings,submitPolicy,approvePolicy,revokeConsent,requestPrivacyAction,decidePrivacyRequest,executeAccountErasure,purgeRetainedContent} from '@/lib/domain/governance'
export type GovernanceState={error?:string;notice?:string}
const text=(form:FormData,key:string)=>String(form.get(key)??'')
export async function saveCompany(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await saveCompanySettings(admin.id,Object.fromEntries(form));return {notice:'Company details saved as an operator-entered record. External verification and legal approval remain required.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function createRetentionPolicy(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await submitPolicy(admin.id,'PRIVACY',{retentionDays:{contact:Number(text(form,'contact')),clinical:Number(text(form,'clinical')),financial:Number(text(form,'financial'))},legalReviewReference:text(form,'reference'),text:text(form,'policyText')},text(form,'reference'));revalidatePath('/admin/governance');return {notice:'Draft policy recorded. It does not enable erasure until approved after review.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function approveReviewPolicy(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await approvePolicy(admin.id,text(form,'id'),text(form,'reviewer'),form.get('checked')==='on');revalidatePath('/admin/governance');return {notice:'Human review attestation recorded for this policy version.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function withdrawConsent(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const user=await requireUser('/account/privacy');try{await revokeConsent(user.id,text(form,'id'));revalidatePath('/account/privacy');return {notice:'Consent withdrawn. New access under that grant is blocked; legally retained records are reviewed separately.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function createPrivacyCase(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const user=await requireUser('/account/privacy');try{await requestPrivacyAction(user.id,text(form,'kind'),text(form,'detail'));revalidatePath('/account/privacy');return {notice:'Privacy request recorded for review.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function reviewPrivacyCase(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await decidePrivacyRequest(admin.id,text(form,'id'),text(form,'next'),text(form,'decision'));revalidatePath('/admin/governance');return {notice:'Review decision recorded.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function executeErasure(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await executeAccountErasure(admin.id,text(form,'id'),form.get('confirmed')==='on');revalidatePath('/admin/governance');return {notice:'Reviewed contact-erasure operation completed; retained records follow the approved retention policy.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function executeRetainedRedaction(_prev:GovernanceState,form:FormData):Promise<GovernanceState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator required.'};try{await purgeRetainedContent(admin.id,text(form,'id'),form.get('confirmed')==='on');revalidatePath('/admin/governance');return {notice:'Eligible retained content redacted; private-object deletion is queued and audited. Financial/audit metadata and backups follow their separate retention obligations.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
