'use server'
import {requireUser,currentAdmin} from '@/lib/auth'
import {revalidatePath} from 'next/cache'
import {DomainError} from '@/lib/domain/errors'
import {publishMedicine,publishPharmacy,setInventory,requestMedicineOrder,transitionMedicineOrder,recordPrescriptionSafety} from '@/lib/domain/pharmacy'
import {submitPolicy} from '@/lib/domain/governance'
export type PharmacyState={error?:string;notice?:string}
const text=(f:FormData,k:string)=>String(f.get(k)??'')
async function run(work:()=>Promise<unknown>,notice:string):Promise<PharmacyState>{try{await work();for(const p of ['/staff/pharmacy','/account/pharmacy','/admin/clinical','/practice/patients'])revalidatePath(p);return {notice}}catch(e){if(e instanceof DomainError)return {error:e.message};if(e instanceof SyntaxError)return {error:'Check the structured policy JSON.'};throw e}}
export async function draftClinicalPolicy(_s:PharmacyState,f:FormData){const a=await currentAdmin();if(!a)return {error:'MFA administrator required.'};return run(()=>submitPolicy(a.id,text(f,'kind'),JSON.parse(text(f,'content')),text(f,'evidence')),'Review draft recorded. Publication requires completed professional review.')}
export async function addMedicine(_s:PharmacyState,f:FormData){const a=await currentAdmin();if(!a)return {error:'MFA administrator required.'};return run(()=>publishMedicine(a.id,{name:text(f,'name'),strength:text(f,'strength'),form:text(f,'form'),species:f.getAll('species'),restrictions:JSON.parse(text(f,'restrictions'))}),'Reviewed catalogue item published.')}
export async function addPharmacy(_s:PharmacyState,f:FormData){const a=await currentAdmin();if(!a)return {error:'MFA administrator required.'};return run(()=>publishPharmacy(a.id,{clinicId:text(f,'clinicId'),name:text(f,'name'),registration:text(f,'registration'),expiresOn:text(f,'expiresOn'),userId:text(f,'userId'),professionalReference:text(f,'professionalReference'),checked:f.get('checked')==='on'}),'Actual pharmacy and pharmacist verification recorded.')}
export async function updateInventory(_s:PharmacyState,f:FormData){const u=await requireUser('/staff/pharmacy');return run(()=>setInventory(u.id,text(f,'partnerId'),text(f,'medicineId'),Number(text(f,'stock')),text(f,'pricePaise')),'Inventory updated.')}
export async function orderMedicine(_s:PharmacyState,f:FormData){const u=await requireUser('/account/pharmacy');return run(()=>requestMedicineOrder(u.id,{partnerId:text(f,'partnerId'),prescriptionId:text(f,'prescriptionId'),addressId:text(f,'addressId'),requestKey:text(f,'requestKey'),lines:[{medicineId:text(f,'medicineId'),quantity:Number(text(f,'quantity'))}],consent:f.get('consent')==='on'}),'Request submitted for pharmacist review. Dispensing requires prescriber safety review and actual payment.')}
export async function updateMedicineOrder(_s:PharmacyState,f:FormData){const u=await requireUser('/staff/pharmacy');return run(()=>transitionMedicineOrder(u.id,text(f,'id'),Number(text(f,'revision')),text(f,'next'),text(f,'reference')),'Fulfilment event recorded.')}
export async function reviewPrescription(_s:PharmacyState,f:FormData){const u=await requireUser('/practice/patients');if(f.get('checked')!=='on')return {error:'Complete and document the clinical safety review first.'};return run(()=>recordPrescriptionSafety(u.id,text(f,'id'),text(f,'decision'),text(f,'detail')),'Prescriber safety decision recorded for this exact signed version.')}
