'use server'
import {currentAdmin,requireUser} from '@/lib/auth'
import {revalidatePath} from 'next/cache'
import {saveProviderApplication,submitProviderApplication,reviewProviderApplication,providerApplication} from '@/lib/domain/providers'
import {DomainError} from '@/lib/domain/errors'
export type ProviderState={error?:string;notice?:string;applicationId?:string;revision?:number}
export async function saveProviderDraft(_prev:ProviderState,form:FormData):Promise<ProviderState>{const user=await requireUser('/join');try{const raw:Record<string,unknown>=Object.fromEntries(form);raw.supportedSpecies=form.getAll('supportedSpecies');const id=await saveProviderApplication(user.id,raw),application=await providerApplication(user.id);revalidatePath('/join');return {notice:'Draft saved. Upload each of the four verification documents, then submit.',applicationId:id,revision:application?.revision}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function submitProviderDraft(_prev:ProviderState,form:FormData):Promise<ProviderState>{const user=await requireUser('/join');try{const id=await submitProviderApplication(user.id,String(form.get('applicationId')??''),form.get('attested')==='on',Number(form.get('revision')));revalidatePath('/join');return {notice:'Submitted for verification. Your profile is not public until approved.',applicationId:id}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
export async function reviewProvider(_prev:ProviderState,form:FormData):Promise<ProviderState>{const admin=await currentAdmin();if(!admin)return {error:'Administrator sign-in required.'};try{await reviewProviderApplication(admin.id,String(form.get('applicationId')??''),String(form.get('decision')??''),String(form.get('reason')??''),{identityMatched:form.get('identityMatched')==='on',registrationChecked:form.get('registrationChecked')==='on',qualificationMatched:form.get('qualificationMatched')==='on',clinicMatched:form.get('clinicMatched')==='on',sourceUrl:String(form.get('sourceUrl')??''),sourceReference:String(form.get('sourceReference')??''),revision:Number(form.get('revision'))});revalidatePath('/admin/providers');revalidatePath('/search');return {notice:'Verification decision recorded.'}}catch(error){if(error instanceof DomainError)return {error:error.message};throw error}}
