import test from 'node:test'
import assert from 'node:assert/strict'
import {freshDb,addUser,addDoctor} from './helpers.mjs'
import {loadServices} from './service-loader.mjs'
test('extended local clinic, dispatch, privacy and pharmacy contracts',async t=>{
 process.env.CARENEST_LOCAL_MODE='1';process.env.AUTH_SECRET='extended-local-test-secret-'.repeat(3)
 const db=await freshDb(),load=loadServices(db),walk=load('lib/domain/walk-ins.ts'),clinical=load('lib/domain/clinical.ts'),home=load('lib/domain/home-visits.ts'),booking=load('lib/domain/bookings.ts'),gov=load('lib/domain/governance.ts'),pharm=load('lib/domain/pharmacy.ts'),billing=load('lib/domain/billing.ts')
 try{
  for(const [id,phone,role]of [['owner','9000000001','patient'],['other','9000000002','patient'],['doctor','9000000003','doctor'],['desk','9000000004','patient'],['pharmacist','9000000005','patient'],['courier','9000000006','patient']])await addUser(db,id,phone,role)
  await db.query("INSERT INTO admins(id,username,password_hash,salt,totp_secret) VALUES('admin','test-admin','unusable','test-salt','encrypted-test-placeholder')")
  await db.query("INSERT INTO clinic.clinics(id,name) VALUES('clinic','Test clinic'),('foreign','Other clinic')")
  await addDoctor(db,'provider',{home_visit:true});await db.query("UPDATE patient.users SET kyc_level='verified',name='Test doctor' WHERE id='doctor'");await db.query("UPDATE provider.doctors SET user_id='doctor',clinic_id='clinic',verified_at=now() WHERE id='provider'")
  await db.query("INSERT INTO clinic.memberships(clinic_id,user_id,role) VALUES('clinic','doctor','clinician'),('clinic','desk','receptionist')")
  let arrival,encounter,rx,address,medicine,partner,order
  const arrivalInput={clinicId:'clinic',doctorId:'provider',name:'Actual patient',phone:'9000000001',sex:'Female',kind:'human',reason:'Actual visit reason',consentAttested:true,requestKey:'actual-walk-in-idempotency-key'}
  await t.test('arrival creates encrypted identity, encounter and invoice atomically without linking by phone',async()=>{
   arrival=await walk.registerWalkIn('desk',arrivalInput);assert.ok(arrival.claimToken)
   const person=await db.one('SELECT * FROM clinic.people');assert.equal(person.owner_id,null);assert.equal(person.encrypted_identity.includes('Actual patient'),false)
   encounter=(await db.one('SELECT id FROM clinic.encounters WHERE walk_in_id=$1',[arrival.id])).id
   assert.equal((await db.one('SELECT user_id FROM clinic.invoices WHERE walk_in_id=$1',[arrival.id])).user_id,null)
   assert.equal((await walk.registerWalkIn('desk',arrivalInput)).claimToken,null)
   await assert.rejects(walk.registerWalkIn('desk',{...arrivalInput,name:'Changed patient'}),e=>e.code==='IDEMPOTENCY')
   await assert.rejects(walk.registerWalkIn('other',{...arrivalInput,requestKey:'foreign-clinic-arrival-intent'}),e=>e.code==='FORBIDDEN')
  })
  await t.test('only assigned clinician starts and signs; private receipt and matching phone are both required',async()=>{
   await assert.rejects(walk.transitionWalkIn('desk',arrival.id,0,'IN_PROGRESS'),e=>e.code==='FORBIDDEN')
   await assert.rejects(clinical.writeClinicalRecord({actorId:'doctor',encounterId:encounter,kind:'chart_notes',body:{diagnosis:'Not started'}}),e=>e.code==='STATE')
   await walk.transitionWalkIn('doctor',arrival.id,0,'IN_PROGRESS')
   rx=await clinical.writeClinicalRecord({actorId:'doctor',encounterId:encounter,kind:'prescriptions',body:{drugs:[{drug:'Reviewed test medicine',dose:'Test dose',frequency:'Reviewed frequency',days:'2'}]}})
   await assert.rejects(clinical.readEncounter('owner',encounter),e=>e.code==='FORBIDDEN')
   await assert.rejects(walk.claimClinicVisit('other',arrival.claimToken,true),e=>e.code==='CLAIM')
   await walk.claimClinicVisit('owner',arrival.claimToken,true)
   assert.equal((await clinical.patientRecords('owner'))[0].id,rx)
   await assert.rejects(walk.claimClinicVisit('owner',arrival.claimToken,true),e=>e.code==='CLAIM')
   await assert.rejects(walk.transitionWalkIn('doctor',arrival.id,0,'ATTENDED'),e=>e.code==='STATE')
  })
  await t.test('owned encrypted addresses and home bookings enforce scope and dispatch revisions',async()=>{
   address=await home.saveAddress('owner',{label:'Home',street:'Actual address',locality:'Test locality',city:'Mumbai',pin:'400001',contactPhone:'9000000001'})
   assert.equal((await db.one('SELECT encrypted_address FROM patient.addresses WHERE id=$1',[address])).encrypted_address.includes('Actual address'),false)
   await db.query("INSERT INTO provider.appointment_slots(slot_id,doctor_id,slot_start,slot_end) VALUES('home-slot','provider',now()+interval '1 hour',now()+interval '2 hours')")
   await assert.rejects(booking.requestAppointment({actorId:'other',doctorId:'provider',slotId:'home-slot',mode:'home_visit',addressId:address,idempotencyKey:'foreign-address-booking-key',consent:true}),e=>e.code==='ADDRESS')
   const b=await booking.requestAppointment({actorId:'owner',doctorId:'provider',slotId:'home-slot',mode:'home_visit',addressId:address,idempotencyKey:'home-address-booking-intent',consent:true})
   await booking.respondAppointment({actorId:'doctor',bookingId:b.id,decision:'confirmed'})
   await home.transitionHomeVisit('desk',b.id,0,'ASSIGNED','desk');await home.transitionHomeVisit('desk',b.id,1,'EN_ROUTE')
   await assert.rejects(home.transitionHomeVisit('desk',b.id,1,'ARRIVED'),e=>e.code==='STATE')
   await assert.rejects(home.dispatchList('other','clinic'),e=>e.code==='FORBIDDEN')
   await booking.cancelAppointment('owner',b.id);assert.equal((await db.one('SELECT state FROM clinic.home_visits WHERE booking_id=$1',[b.id])).state,'CANCELLED')
  })
  await t.test('pharmacy cannot publish without professional policy; actual partner verification and catalogue required',async()=>{
   await assert.rejects(pharm.publishMedicine('admin',{name:'Reviewed test medicine',strength:'Reviewed strength',form:'Test form',species:['human']}),e=>e.code==='POLICY')
   const policy=await gov.submitPolicy('admin','PRESCRIBING',{text:'Test-only professional policy',species:['human']},'Test-only recorded evidence');await gov.approvePolicy('admin',policy,'doctor',true)
   const wrongScope=await gov.submitPolicy('admin','PRESCRIBING',{text:'Unapproved veterinary draft',species:['dog']},'Synthetic scope rejection evidence');await assert.rejects(gov.approvePolicy('admin',wrongScope,'doctor',true),e=>e.code==='REVIEW_SCOPE')
   medicine=await pharm.publishMedicine('admin',{name:'Reviewed test medicine',strength:'Reviewed strength',form:'Test form',species:['human'],restrictions:{deliveryAllowed:true}})
   partner=await pharm.publishPharmacy('admin',{clinicId:'clinic',name:'Test pharmacy',registration:'Test licence only',expiresOn:'2099-01-01',userId:'pharmacist',professionalReference:'Test pharmacist reference only',checked:true})
   await db.query("INSERT INTO pharmacy.memberships(partner_id,user_id,role) VALUES($1,'courier','DISPATCH')",[partner])
   await pharm.setInventory('pharmacist',partner,medicine,10,'2500')
   assert.equal((await pharm.pharmacyCatalogue())[0].available,10)
  })
  await t.test('owned medicine requests are idempotent and approval needs current prescriber safety review',async()=>{
   const input={partnerId:partner,prescriptionId:rx,addressId:address,requestKey:'medicine-order-intent-key',lines:[{medicineId:medicine,quantity:2}],consent:true}
   await assert.rejects(pharm.requestMedicineOrder('other',input),e=>e.code==='PRESCRIPTION')
   order=await pharm.requestMedicineOrder('owner',input);assert.equal(await pharm.requestMedicineOrder('owner',input),order)
   const pendingInvoice=await db.one('SELECT id FROM clinic.invoices WHERE pharmacy_order_id=$1',[order]);await assert.rejects(billing.recordClinicPayment('pharmacist',pendingInvoice.id,'cash','5000'),e=>e.code==='STATE')
   await assert.rejects(pharm.requestMedicineOrder('owner',{...input,lines:[{medicineId:medicine,quantity:3}]}),e=>e.code==='IDEMPOTENCY')
   await assert.rejects(pharm.transitionMedicineOrder('pharmacist',order,0,'APPROVED'),e=>e.code==='SAFETY')
   await pharm.recordPrescriptionSafety('doctor',rx,'APPROVED','Test-only documented safety review and actual checks')
   await pharm.transitionMedicineOrder('pharmacist',order,0,'APPROVED');assert.equal((await db.one('SELECT reserved FROM pharmacy.inventory WHERE partner_id=$1',[partner])).reserved,2)
   await pharm.transitionMedicineOrder('pharmacist',order,1,'PACKED');await assert.rejects(pharm.transitionMedicineOrder('pharmacist',order,2,'DISPATCHED'),e=>e.code==='PAYMENT')
  })
  await t.test('courier sees minimum dispatch information; only licensed cashier settles correct pharmacy invoice',async()=>{
   const courier=await pharm.pharmacyWork('courier');assert.equal(courier.orders[0].prescription,null);assert.deepEqual(courier.orders[0].lines,[]);assert.equal(courier.orders[0].address.street,'Actual address')
   const i=await db.one('SELECT id FROM clinic.invoices WHERE pharmacy_order_id=$1',[order])
   await assert.rejects(billing.recordClinicPayment('courier',i.id,'cash','5000'),e=>e.code==='FORBIDDEN')
   await billing.recordClinicPayment('pharmacist',i.id,'cash','5000');await pharm.transitionMedicineOrder('pharmacist',order,2,'DISPATCHED','Actual tracking receipt')
   await pharm.transitionMedicineOrder('courier',order,3,'DELIVERED','Actual delivery receipt');assert.deepEqual(await db.one('SELECT stock,reserved FROM pharmacy.inventory WHERE partner_id=$1',[partner]),{stock:8,reserved:0})
  })
  await t.test('withdrawal prevents new clinical and pharmacy sharing while owner retains care access',async()=>{
   await walk.transitionWalkIn('doctor',arrival.id,1,'ATTENDED'); const sharing=await db.one("SELECT id FROM patient.consents WHERE actor_id='owner' AND purpose='walk-in-sharing'");await gov.revokeConsent('owner',sharing.id)
   await assert.rejects(clinical.readEncounter('doctor',encounter),e=>e.code==='CONSENT')
   assert.equal((await clinical.readEncounter('owner',encounter)).records[0].id,rx)
   const pharmacySharing=await db.one("SELECT id FROM patient.consents WHERE actor_id='owner' AND purpose='pharmacy-sharing'");await gov.revokeConsent('owner',pharmacySharing.id)
   const staff=await pharm.pharmacyWork('pharmacist');assert.equal(staff.orders[0].prescription,null);assert.equal(staff.orders[0].address,null)
  })
  await t.test('privacy requests are scoped and erasure cannot bypass approved retention and holds',async()=>{
   const id=await gov.requestPrivacyAction('owner','DELETION','Actual privacy deletion request')
   await assert.rejects(gov.requestPrivacyAction('owner','DELETION','Duplicate request'),e=>e.code==='DUPLICATE')
   assert.equal((await gov.privacyRequests('other')).length,0)
   await gov.decidePrivacyRequest('admin',id,'APPROVED','Actual documented review decision')
   await assert.rejects(gov.executeAccountErasure('admin',id,true),e=>e.code==='POLICY')
   const p=await gov.submitPolicy('admin','PRIVACY',{retentionDays:{contact:0,clinical:365,financial:365},legalReviewReference:'Test-only legal policy reference'},'Test-only legal evidence');await gov.approvePolicy('admin',p,'doctor',true)
   await db.query("INSERT INTO retention_holds(id,user_id,reason,created_by) VALUES('hold','owner','Test hold','admin')")
   await assert.rejects(gov.executeAccountErasure('admin',id,true),e=>e.code==='HOLD')
   await db.query("DELETE FROM retention_holds WHERE id='hold'");await gov.executeAccountErasure('admin',id,true)
   assert.equal((await db.one("SELECT status FROM patient.users WHERE id='owner'")).status,'ERASED')
   assert.equal((await db.one('SELECT body FROM documents WHERE id=$1',[rx])).body._encrypted.includes('Actual patient'),false)
   await assert.rejects(gov.purgeRetainedContent('admin',id,true),e=>e.code==='RETENTION')
   const immediate=await gov.submitPolicy('admin','PRIVACY',{retentionDays:{contact:0,clinical:0,financial:0},legalReviewReference:'Test-only immediate redaction policy'},'Synthetic test-only legal evidence');await gov.approvePolicy('admin',immediate,'doctor',true)
   await gov.purgeRetainedContent('admin',id,true)
   assert.equal(clinical.decodeRecord(rx,(await db.one('SELECT body FROM documents WHERE id=$1',[rx])).body).retentionErased,true)
   assert.equal(Number((await db.one('SELECT count(*) n FROM document_maintenance_permits')).n),0)
   await assert.rejects(db.query('UPDATE documents SET body=$2::jsonb WHERE id=$1',[rx,JSON.stringify({changed:true})]),/append-only/)
  })
 }finally{await db.close()}
})
