import test from 'node:test'
import assert from 'node:assert/strict'
import {jwtVerify} from 'jose'
import {AccessToken,TrackSource} from 'livekit-server-sdk'
import {freshDb,addUser,addDoctor} from './helpers.mjs'
import {loadServices} from './service-loader.mjs'

test('LiveKit consultation enforces current participants, consent, token grants and cleanup',async t=>{
 process.env.CARENEST_LOCAL_MODE='1';process.env.AUTH_SECRET='livekit-test-'.repeat(5)
 process.env.LIVEKIT_URL='ws://127.0.0.1:7880';process.env.LIVEKIT_API_KEY='synthetic-key';process.env.LIVEKIT_API_SECRET='synthetic-secret-'.repeat(4)
 const db=await freshDb(),rooms=new Map();let creates=0,deletes=0,createHook
 class MediaApi{
  async createRoom({name}){creates++;if(!rooms.has(name))rooms.set(name,{name,participants:[]});if(createHook)await createHook();return {name}}
  async deleteRoom(name){deletes++;rooms.delete(name)}
  async listRooms(){return [...rooms.values()]}
  async listParticipants(name){return rooms.get(name)?.participants??[]}
  async removeParticipant(name,id){rooms.get(name).participants=rooms.get(name).participants.filter(p=>p.identity!==id)}
 }
 const load=loadServices(db,{'livekit-server-sdk':{AccessToken,TrackSource,RoomServiceClient:MediaApi}}),lk=load('lib/domain/livekit.ts'),booking=load('lib/domain/bookings.ts'),video=load('lib/domain/video.ts')
 try{
  for(const [id,phone,role]of [['patient','9000000001','patient'],['stranger','9000000002','patient'],['doctor','9000000003','doctor']])await addUser(db,id,phone,role)
  await addDoctor(db,'provider',{video:true});await db.exec("UPDATE provider.doctors SET user_id='doctor',verified_at=now();UPDATE patient.users SET kyc_level='verified' WHERE id='doctor'")
  async function visit(slot){await db.query("INSERT INTO provider.appointment_slots(slot_id,doctor_id,slot_start,slot_end) VALUES($1,'provider',now()+interval '5 minutes',now()+interval '20 minutes')",[slot]);const b=await booking.requestAppointment({actorId:'patient',doctorId:'provider',slotId:slot,mode:'video',idempotencyKey:slot+'-request-key',consent:true,videoConsent:true});await booking.respondAppointment({actorId:'doctor',bookingId:b.id,decision:'confirmed'});return b}
  const b=await visit('livekit-slot')
  await t.test('loopback Host normalization permits the actual local origin without trusting foreign hosts',()=>{const {sameOrigin}=load('lib/http.ts');assert.equal(sameOrigin(new Request('http://localhost:3000/api',{headers:{host:'127.0.0.1:3000',origin:'http://127.0.0.1:3000'}})),true);for(const [host,origin]of [['foreign.example:3000','http://foreign.example:3000'],['127.0.0.1:4000','http://127.0.0.1:4000'],['127.0.0.1:3000','https://foreign.example']])assert.equal(sameOrigin(new Request('http://localhost:3000/api',{headers:{host,origin}})),false)})
  await t.test('only a loopback server is accepted in local mode',()=>{const prior=process.env.LIVEKIT_URL;for(const url of ['wss://remote.example','ws://127.0.0.1:7880/?key=secret','http://127.0.0.1:7880']){process.env.LIVEKIT_URL=url;assert.throws(()=>lk.livekitConfiguration(),e=>e.code==='LIVEKIT_CONFIGURATION')}process.env.LIVEKIT_URL=prior})
  await t.test('Zoom cannot connect and retired SDK/webhook endpoints make no external calls',async()=>{assert.equal(video.integrationConfigured('zoom'),false);await assert.rejects(video.beginVideoConnection('doctor','zoom','http://127.0.0.1:3000'),e=>e.code==='PROVIDER');assert.equal((await load('app/api/webhooks/zoom/route.ts').POST()).status,410);assert.equal((await load('app/api/video/[bookingId]/embedded/route.ts').GET()).status,410)})
  let patientClaims,hostClaims,name
  await t.test('tokens bind opaque identity to one room for 30 seconds with camera/microphone only',async()=>{await video.provisionVideo(b.id);const p=await lk.livekitJoin('patient',b.id),h=await lk.livekitJoin('doctor',b.id);patientClaims=(await jwtVerify(p.participantToken,new TextEncoder().encode(process.env.LIVEKIT_API_SECRET))).payload;hostClaims=(await jwtVerify(h.participantToken,new TextEncoder().encode(process.env.LIVEKIT_API_SECRET))).payload;name=patientClaims.video.room;assert.equal(creates,3);assert.equal(patientClaims.exp-patientClaims.nbf,30);assert.match(name,/^cn_[a-f0-9]{32}$/);assert.notEqual(patientClaims.sub,'patient');assert.notEqual(patientClaims.sub,hostClaims.sub);assert.equal(patientClaims.video.roomJoin,true);assert.equal(patientClaims.video.roomAdmin,undefined);assert.equal(patientClaims.video.roomRecord,undefined);assert.equal(patientClaims.video.canPublishData,false);assert.deepEqual(patientClaims.video.canPublishSources,['camera','microphone'])})
  await t.test('wrong participant, inactive practitioner, expired window and revoked consent fail closed',async()=>{await assert.rejects(lk.livekitJoin('stranger',b.id),e=>e.code==='UNAVAILABLE');await db.query("UPDATE provider.doctors SET status='SUSPENDED'");await assert.rejects(lk.livekitJoin('patient',b.id),e=>e.code==='UNAVAILABLE');await db.exec("UPDATE provider.doctors SET status='ACTIVE';UPDATE patient.bookings SET starts_at=now()+interval '2 hours',ends_at=now()+interval '3 hours'");await assert.rejects(lk.livekitJoin('patient',b.id),e=>e.code==='WINDOW');await db.exec("UPDATE patient.bookings SET starts_at=now()+interval '5 minutes',ends_at=now()+interval '20 minutes';UPDATE patient.consents SET revoked_at=now() WHERE purpose='video-provider'");await assert.rejects(lk.livekitJoin('patient',b.id),e=>e.code==='UNAVAILABLE');await db.query('UPDATE patient.consents SET revoked_at=NULL')})
  await t.test('active fence removes unexpected identity and closes revoked rooms',async()=>{rooms.get(name).participants=[{identity:patientClaims.sub},{identity:hostClaims.sub},{identity:'intruder'}];assert.equal((await lk.reconcileLivekit()).removed,1);await db.query("UPDATE patient.consents SET revoked_at=now() WHERE purpose='video-provider'");assert.equal((await lk.reconcileLivekit()).closed,1);assert.equal(rooms.has(name),false);await db.query('UPDATE patient.consents SET revoked_at=NULL');await assert.rejects(lk.livekitJoin('patient',b.id),e=>e.code==='CLOSED')})
  await t.test('late creation after cancellation is deleted; idempotent cleanup remains available',async()=>{await booking.cancelAppointment('patient',b.id);const late=await visit('late-livekit');createHook=async()=>booking.cancelAppointment('patient',late.id);await assert.rejects(video.provisionVideo(late.id),e=>e.code==='UNAVAILABLE');createHook=undefined;assert.equal((await db.one('SELECT state FROM video_sessions WHERE booking_id=$1',[late.id])).state,'CANCELLED');await video.cancelVideo(late.id);assert.ok(deletes>=2)})
  await t.test('cleanup of a future empty room does not permanently close its appointment',async()=>{const future=await visit('future-livekit');await db.query("UPDATE patient.bookings SET starts_at=now()+interval '2 hours',ends_at=now()+interval '3 hours' WHERE id=$1",[future.id]);await video.provisionVideo(future.id);await lk.reconcileLivekit();assert.equal((await db.one('SELECT state FROM video_sessions WHERE booking_id=$1',[future.id])).state,'READY');await db.query("UPDATE patient.bookings SET starts_at=now()+interval '5 minutes',ends_at=now()+interval '20 minutes' WHERE id=$1",[future.id]);assert.equal((await lk.livekitJoin('patient',future.id)).expiresIn,30)})
  await t.test('token route rejects cross-origin and anonymous requests',async()=>{const routes=loadServices(db,{'@/lib/auth':{currentUser:async()=>null}})('app/api/video/[bookingId]/livekit/route.ts'),ctx={params:Promise.resolve({bookingId:b.id})};assert.equal((await routes.POST(new Request('http://localhost/api/video/id/livekit',{method:'POST',headers:{origin:'https://foreign.example'}}),ctx)).status,403);assert.equal((await routes.POST(new Request('http://localhost/api/video/id/livekit',{method:'POST',headers:{origin:'http://localhost'}}),ctx)).status,401)})
 }finally{await db.close();for(const key of ['LIVEKIT_URL','LIVEKIT_API_KEY','LIVEKIT_API_SECRET'])delete process.env[key]}
})
