import test from 'node:test'
import assert from 'node:assert/strict'
import {freshDb,addUser,addDoctor} from './helpers.mjs'
import {loadServices} from './service-loader.mjs'
test('mobile access, offline intents, interoperability and legacy quarantine',async t=>{
 process.env.CARENEST_LOCAL_MODE='1';process.env.ENABLE_PAYMENTS='1';process.env.CASHFREE_ENV='sandbox';process.env.CASHFREE_CLIENT_ID='TEST_mobile_fixture';process.env.CASHFREE_CLIENT_SECRET='fixture_mobile_private';process.env.AUTH_SECRET='mobile-maintenance-test-secret-'.repeat(3)
 const db=await freshDb(),load=loadServices(db),mobile=load('lib/domain/mobile.ts'),cases=load('lib/domain/integration-cases.ts'),reconcile=load('lib/domain/reconciliation.ts'),secrets=load('lib/secrets.ts')
 try{
  await addUser(db,'owner','9000000001');await addUser(db,'other','9000000002');await addUser(db,'doctor','9000000003','doctor');await db.query("UPDATE patient.users SET kyc_level='verified' WHERE id='doctor'");await db.query("INSERT INTO clinic.clinics(id,name) VALUES('clinic','Test clinic')");await addDoctor(db,'provider');await db.query("UPDATE provider.doctors SET user_id='doctor',clinic_id='clinic',verified_at=now() WHERE id='provider'");await db.query("INSERT INTO admins(id,username,password_hash,salt,totp_secret) VALUES('admin','test-admin','unusable','test-salt','encrypted-test')")
  let session,booked,encounter
  await t.test('pairing is one-use, session token is hashed and revocation is immediate',async()=>{const code=await mobile.pairMobile('owner');session=await mobile.exchangeMobilePairing(code);assert.notEqual((await db.one('SELECT token_hash FROM mobile_devices')).token_hash,session.token);await assert.rejects(mobile.exchangeMobilePairing(code),e=>e.code==='PAIRING');const request=new Request('http://localhost:3000/api/mobile/state',{headers:{Authorization:'Bearer '+session.token}});assert.equal((await mobile.mobileActor(request)).user_id,'owner');await mobile.revokeMobileDevice('owner',session.deviceId);await assert.rejects(mobile.mobileActor(request),e=>e.code==='AUTH');await assert.rejects(mobile.pairMobile('doctor'),e=>e.code==='FORBIDDEN')})
  await t.test('offline intents make one server booking and cannot overwrite reused intent details',async()=>{await db.query("INSERT INTO provider.appointment_slots(slot_id,doctor_id,slot_start,slot_end) VALUES('slot','provider',now()+interval '1 hour',now()+interval '2 hours')");const input={key:'offline-booking-intent-key',kind:'BOOK',payload:{doctorId:'provider',slotId:'slot',consent:true}};booked=await mobile.syncMobileIntent('owner',input);assert.equal(booked.state,'AWAITING_PAYMENT');assert.equal(booked.checkoutPath,'/account/checkout/'+booked.bookingId);assert.equal((await db.one('SELECT state FROM clinic.invoices WHERE booking_id=$1',[booked.bookingId])).state,'UNPAID');assert.deepEqual(await mobile.syncMobileIntent('owner',input),booked);assert.equal(Number((await db.one('SELECT count(*) n FROM patient.bookings')).n),1);await assert.rejects(mobile.syncMobileIntent('owner',{...input,payload:{...input.payload,slotId:'different'}}),e=>e.code==='IDEMPOTENCY');await assert.rejects(mobile.syncMobileIntent('other',{key:'offline-foreign-cancel-key',kind:'CANCEL',payload:{bookingId:booked.bookingId,revision:0}}),e=>e.code==='FORBIDDEN');assert.equal((await mobile.mobileSnapshot('owner')).appointments[0].id,booked.bookingId)})
  await t.test('partner cases are owned, encrypted and intake-only; exports exclude veterinary subjects',async()=>{const input={provider:'ABDM',bookingId:booked.bookingId,key:'interoperability-request-key',detail:'Actual human interoperability intake request',reference:'',consent:true},id=await cases.requestIntegrationCase('owner',input);assert.equal(await cases.requestIntegrationCase('owner',input),id);assert.equal((await db.one('SELECT state FROM integration_cases')).state,'WAITING_PARTNER');assert.equal((await db.one('SELECT encrypted_payload FROM integration_cases')).encrypted_payload.includes('Actual human'),false);await assert.rejects(cases.exportHumanRecordBundle('other',id),e=>e.code==='CONSENT');const bundle=await cases.exportHumanRecordBundle('owner',id);assert.equal(bundle.resourceType,'Bundle');await assert.rejects(cases.reviewIntegrationCase('admin',id,0,'APPROVED','Invented partner approval'),e=>e.code==='STATE');await cases.reviewIntegrationCase('admin',id,0,'IN_REVIEW','Actual intake review');await assert.rejects(cases.reviewIntegrationCase('admin',id,0,'CLOSED','Stale review'),e=>e.code==='STATE')})
  await t.test('legacy records are encrypted and ownership is not guessed; mismatched imports are rejected',async()=>{const i=await db.one('SELECT id,total_paise FROM clinic.invoices WHERE booking_id=$1',[booked.bookingId]);await db.query("INSERT INTO payment_orders(id,invoice_id,user_id,amount_paise,gateway,external_id,idempotency_key) VALUES('mobile-payment',$1,'owner',$2,'cashfree','mobile-order','mobile-money-fixture')",[i.id,String(i.total_paise)]);await load('lib/domain/billing.ts').settleCapturedPayment('mobile-paid','mobile-order','1000',String(i.total_paise),'INR');encounter=(await db.one('SELECT id FROM clinic.encounters')).id;await db.query("INSERT INTO documents(id,collection,subject_id,body) VALUES('legacy','chart_notes','owner',$1::jsonb)",[JSON.stringify({patientId:'owner',doctorId:'provider',diagnosis:'Actual source note'})]);assert.equal(await reconcile.scanLegacyDocuments('admin'),1);const row=await db.one("SELECT body FROM documents WHERE id='legacy'");assert.ok(row.body._encrypted);assert.equal(row.body._encrypted.includes('Actual source'),false);const review=(await reconcile.reconciliationCases('admin'))[0];await assert.rejects(reconcile.reconcileDocument('admin',review.id,'missing','Source ownership review evidence',true),e=>e.code==='ENCOUNTER');await reconcile.reconcileDocument('admin',review.id,encounter,'Actual original source identity review',true);assert.equal((await load('lib/domain/clinical.ts').patientRecords('owner'))[0].body.imported,true);assert.equal((await db.one("SELECT owner_id FROM documents WHERE id='legacy'")).owner_id,'owner')})
  await t.test('named encryption keys preserve old reads and authenticated context during rotation',async()=>{const old=secrets.encryptSecret('Private value','test:context');process.env.DATA_ENCRYPTION_KEYRING=JSON.stringify({rotation:'2'.repeat(64)});process.env.DATA_ENCRYPTION_ACTIVE_ID='rotation';try{assert.equal(secrets.decryptSecret(old,'test:context'),'Private value');const next=secrets.encryptSecret('Private value','test:context');assert.ok(next.startsWith('v3:rotation:'));assert.equal(secrets.decryptSecret(next,'test:context'),'Private value');assert.throws(()=>secrets.decryptSecret(next,'wrong:context'));
   const original=(await db.one("SELECT body FROM documents WHERE id='legacy'")).body,source=secrets.decryptSecret(original._encrypted,'clinical:legacy'),replacement={_encrypted:secrets.encryptSecret(source,'clinical:legacy')}
   await db.query("INSERT INTO document_maintenance_permits(document_id,operation,old_body,new_body,approved_by) VALUES('legacy','KEY_ROTATION',$1::jsonb,$2::jsonb,'offline-local-maintenance')",[JSON.stringify(original),JSON.stringify(replacement)])
   await assert.rejects(db.query("UPDATE documents SET owner_id='other',body=$1::jsonb WHERE id='legacy'",[JSON.stringify(replacement)]),/append-only/)
   await db.query("UPDATE documents SET body=$1::jsonb WHERE id='legacy'",[JSON.stringify(replacement)])
   assert.equal(secrets.decryptSecret((await db.one("SELECT body FROM documents WHERE id='legacy'")).body._encrypted,'clinical:legacy'),source);assert.equal(Number((await db.one('SELECT count(*) n FROM document_maintenance_permits')).n),0)
   await assert.rejects(db.query("UPDATE documents SET body=$1::jsonb WHERE id='legacy'",[JSON.stringify(original)]),/append-only/)
   process.env.DATA_ENCRYPTION_KEYRING='{}';assert.throws(()=>secrets.decryptSecret(next,'test:context'),/unavailable/)}finally{delete process.env.DATA_ENCRYPTION_ACTIVE_ID;delete process.env.DATA_ENCRYPTION_KEYRING}})
 }finally{await db.close()}
})
