'use client'
import {useState,useEffect} from 'react'
import Link from 'next/link'
import {LiveKitRoom,GridLayout,ParticipantTile,ControlBar,RoomAudioRenderer,useTracks} from '@livekit/components-react'
import {Track} from 'livekit-client'
import '@livekit/components-styles'
type Credentials={serverUrl:string;participantToken:string}
function CallControls(){const tracks=useTracks([{source:Track.Source.Camera,withPlaceholder:true}],{onlySubscribed:false});return <div className="flex h-full flex-col"><GridLayout tracks={tracks} className="min-h-0 flex-1"><ParticipantTile/></GridLayout><RoomAudioRenderer/><ControlBar controls={{camera:true,microphone:true,leave:true,chat:false,screenShare:false,settings:false}} saveUserChoices={false}/></div>}
export function LivekitConsultation({bookingId}:{bookingId:string}){
 const [credentials,setCredentials]=useState<Credentials|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Join when you are ready. Your camera and microphone start off.'),[connected,setConnected]=useState(false)
 useEffect(()=>{if(!connected)return;const timer=setInterval(async()=>{try{const response=await fetch(`/api/video/${encodeURIComponent(bookingId)}/livekit`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',cache:'no-store'});if(!response.ok){setCredentials(null);setConnected(false);setMessage('Call access changed. Return to your appointments or contact the clinic.')}}catch{setCredentials(null);setConnected(false);setMessage('Connection check failed. Rejoin when your connection recovers.')}},20000);return()=>clearInterval(timer)},[connected,bookingId])
 async function join(){setBusy(true);try{const response=await fetch(`/api/video/${encodeURIComponent(bookingId)}/livekit`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',cache:'no-store'}),body=await response.json();if(!response.ok)throw new Error(body.error??'The call could not be joined.');setCredentials(body);setMessage('Connecting…')}catch(e){setMessage(e instanceof Error?e.message:'The call could not be joined.')}finally{setBusy(false)}}
 return <section className="mt-6 overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm"><div className="p-5"><p role="status" className="leading-7">{message}</p><p className="mt-2 text-sm text-muted-foreground">Only the booked patient or pet owner and assigned clinician can join. Recording, chat and screen sharing are disabled. This call is not for emergencies.</p>{!credentials&&<button className="care-button mt-5" onClick={join} disabled={busy}>{busy?'Preparing call…':'Join video consultation'}</button>}</div>{credentials&&<LiveKitRoom token={credentials.participantToken} serverUrl={credentials.serverUrl} connect audio={false} video={false} data-lk-theme="default" style={{height:'min(75vh, 800px)',minHeight:420}} onConnected={()=>{setConnected(true);setMessage('Connected. Use the call controls to turn on your microphone or camera.')}} onDisconnected={()=>{setCredentials(null);setConnected(false);setMessage('You left the call. You can rejoin while the appointment is active.')}} onError={()=>{setCredentials(null);setConnected(false);setMessage('The call connection failed. Check the local video service and try again.')}}><CallControls/></LiveKitRoom>}<div className="border-t border-border p-5"><Link href="/account/history" className="inline-flex min-h-11 items-center text-sm font-semibold text-primary">View consultation history</Link></div></section>
}
