'use client'
import {useActionState} from 'react'
import {addWalkIn,changeWalkIn,claimVisit,addAddress,changeDispatch,type OperationsState} from '@/app/actions/operations'
type Choice={id:string;name:string}
export function WalkInForm({clinicId,doctors,requestKey}:{clinicId:string;doctors:Choice[];requestKey:string}){
 const[state,action,pending]=useActionState(addWalkIn,{} as OperationsState)
 return <form action={action} className="space-y-4 rounded-2xl border border-border bg-card p-5"><h2 className="text-xl">Register an arrival</h2><input type="hidden" name="clinicId" value={clinicId}/><input type="hidden" name="requestKey" value={requestKey}/><label>Practitioner<select name="doctorId" className="field" required>{doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Care recipient<select name="kind" className="field"><option value="human">Person</option><option value="pet">Pet</option></select></label>{[['name','Patient or pet name'],['phone','Patient or guardian’s phone'],['guardian','Guardian name for a pet'],['sex','Sex or gender, if given']].map(([name,label])=><label key={name} className="block">{label}<input name={name} required={['name','phone'].includes(name)} maxLength={name==='phone'?16:80} className="field"/></label>)}<label className="block">Birth date, if known<input name="dob" type="date" className="field"/></label><label>Pet species<select name="species" className="field"><option value="">Person / not applicable</option>{['dog','cat','rabbit','bird','other'].map(s=><option key={s}>{s}</option>)}</select></label><label>Private reason for visit<textarea name="reason" maxLength={2000} className="field"/></label><label className="flex gap-3 text-sm"><input name="consentAttested" type="checkbox" required/>I obtained the patient or guardian’s actual consent to recording and sharing this encounter with the assigned practitioner</label><button disabled={pending} className="care-button">Record arrival</button><p role="status">{state.error??state.notice}</p>{state.claimToken&&<aside className="rounded-xl bg-soft p-4 text-sm"><p>Private one-time visit receipt. It also requires the matching verified phone and expires in seven days.</p><code className="mt-3 block break-all select-all">{state.claimToken}</code><a href="/account/claim" className="mt-3 block text-primary">Patient claim page</a></aside>}</form>
}
export function WalkInActions({id,revision,state}:{id:string;revision:number;state:string}){const[result,action,pending]=useActionState(changeWalkIn,{} as OperationsState),choices=state==='WAITING'?['IN_PROGRESS','NO_SHOW','CANCELLED']:state==='IN_PROGRESS'?['ATTENDED']:[];return <form action={action} className="mt-4 space-y-3"><input name="id" type="hidden" value={id}/><input name="revision" type="hidden" value={revision}/>{choices.length>0&&<><select name="next" className="field">{choices.map(next=><option key={next}>{next}</option>)}</select><button disabled={pending} className="care-button">Update arrival</button></>}<p role="status" className="text-sm">{result.error??result.notice}</p></form>}
export function ClaimVisitForm(){const[state,action,pending]=useActionState(claimVisit,{} as OperationsState);return <form action={action} className="space-y-4"><label>Private receipt from your clinic<input name="token" required minLength={40} maxLength={80} autoComplete="off" className="field"/></label><label className="flex gap-3 text-sm"><input name="confirmed" type="checkbox" required/>This is my visit or my dependent’s visit, and I authorize linking it to this account</label><button disabled={pending} className="care-button">Claim visit</button><p role="status">{state.error??state.notice}</p></form>}
export function AddressForm(){const[state,action,pending]=useActionState(addAddress,{} as OperationsState);return <form action={action} className="space-y-4 rounded-2xl border border-border bg-card p-5"><h2 className="text-xl">Add a private address</h2>{[['label','Label, such as Home'],['street','Flat, building and street'],['locality','Locality'],['city','City'],['pin','PIN code'],['contactPhone','Contact phone'],['instructions','Arrival instructions, if needed']].map(([name,label])=><label key={name} className="block">{label}<input name={name} required={name!=='instructions'} maxLength={name==='instructions'?500:name==='street'?300:100} className="field"/></label>)}<button disabled={pending} className="care-button">Save address</button><p role="status">{state.error??state.notice}</p></form>}
export function DispatchForm({id,revision,state,staff}:{id:string;revision:number;state:string;staff:Choice[]}){const[result,action,pending]=useActionState(changeDispatch,{} as OperationsState),choices:Record<string,string[]>={UNASSIGNED:['ASSIGNED'],ASSIGNED:['EN_ROUTE'],EN_ROUTE:['ARRIVED'],ARRIVED:['COMPLETED']};return <form action={action} className="mt-4 space-y-3"><input name="id" value={id} type="hidden"/><input name="revision" value={revision} type="hidden"/>{choices[state]&&<><select name="next" className="field">{choices[state].map(s=><option key={s}>{s}</option>)}</select>{state==='UNASSIGNED'&&<label>Assigned staff<select name="assignee" className="field">{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<button disabled={pending} className="care-button">Record dispatch event</button></>}<p role="status">{result.error??result.notice}</p></form>}
