'use client'
import {useActionState} from 'react'
import {saveProviderDraft,submitProviderDraft,type ProviderState} from '@/app/actions/providers'
import {FileUpload} from './file-upload'
export function ProviderApplicationForm({applicationId,initial}:{applicationId?:string;initial?:Record<string,unknown>}) {
 const [state,action,pending]=useActionState(saveProviderDraft,{} as ProviderState),[submitted,submit,submitPending]=useActionState(submitProviderDraft,{} as ProviderState)
 const id=state.applicationId??applicationId
 return <div className="space-y-5"><form action={action} className="rounded-2xl border border-border bg-card p-5"><div className="grid gap-4 sm:grid-cols-2">{[['name','Practitioner name'],['speciality','Specialty'],['qualification','Qualifications'],['registration','Professional registration number'],['council','Registering council'],['clinic','Clinic name'],['address','Clinic address'],['city','City'],['pin','PIN code'],['languages','Languages, comma separated'],['fee','Consultation fee (whole rupees)'],['experience','Years of experience']].map(([name,label])=><label key={name} className="text-sm">{label}<input name={name} defaultValue={String(initial?.[name]??'')} required type={['fee','experience'].includes(name)?'number':'text'} min="0" maxLength={300} className="field mt-2"/></label>)}<label>Provider type<select name="kind" defaultValue={String(initial?.kind??'human')} className="field mt-2"><option value="human">Human healthcare</option><option value="vet">Veterinary care</option></select></label><fieldset><legend className="text-sm">Veterinary species</legend><div className="flex flex-wrap gap-3">{['dog','cat','rabbit','bird','other'].map(s=><label key={s} className="inline-flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="supportedSpecies" value={s} defaultChecked={Array.isArray(initial?.supportedSpecies)?initial.supportedSpecies.includes(s):['dog','cat'].includes(s)}/>{s}</label>)}</div></fieldset></div><p role="status" className="mt-4 text-sm">{state.error??state.notice}</p><button disabled={pending} className="care-button mt-4">{pending?'Saving…':'Save verification draft'}</button></form>{id&&<><FileUpload applicationId={id}/><form action={submit} className="rounded-2xl border border-border bg-card p-5"><input name="applicationId" type="hidden" value={id}/><p className="text-sm">Submitting records a verification case. An operator must check your registration and evidence before publication.</p><button disabled={submitPending} className="care-button mt-4">{submitPending?'Submitting…':'Submit for verification'}</button><p role="status" className="mt-3 text-sm">{submitted.error??submitted.notice}</p></form></>}</div>
}
