import Link from 'next/link'
import {requireUser} from '@/lib/auth'
import {pharmacyWork,inventoryForStaff} from '@/lib/domain/pharmacy'
import {getDb} from '@/lib/db/client'
import {InventoryForm,MedicineOrderActions} from '@/components/pharmacy-forms'
import {BillingForm} from '@/components/billing-form'
import {ClinicalRecordBody} from '@/components/clinical-record-body'
export const dynamic='force-dynamic'
export default async function PharmacyDesk(){const u=await requireUser('/staff/pharmacy'),work=await pharmacyWork(u.id),inventory=await inventoryForStaff(u.id),medicines=work.partners.some(p=>p.role==='PHARMACIST')?await getDb().query<{id:string;name:string}>("SELECT id,name||' · '||strength name FROM clinical_catalogue WHERE status='ACTIVE' ORDER BY name LIMIT 500"):[];return <main className="care-container py-10"><Link href="/staff">← Staff workspace</Link><h1 className="my-5 text-3xl">Pharmacy fulfilment</h1>{!work.partners.length?<p>No current licensed pharmacy assignment is configured for your account.</p>:<><section className="grid gap-6 lg:grid-cols-2">{work.partners.some(p=>p.role==='PHARMACIST')&&<InventoryForm partners={work.partners.filter(p=>p.role==='PHARMACIST')} medicines={medicines}/>}<div>{inventory.map(i=><p className="my-3" key={i.partner_id+':'+i.catalogue_id}>{i.partner_name} · {i.name} · stock {i.stock}, reserved {i.reserved}</p>)}</div></section><section className="mt-6 grid gap-5 lg:grid-cols-2">{work.orders.map(o=><article key={o.id} className="rounded-2xl border p-5"><h2 className="text-xl">{o.partner_name} · {o.state}</h2>{o.prescription&&<ClinicalRecordBody body={o.prescription}/>}<ul>{o.lines.map(l=><li key={l.name+l.strength}>{l.name} · {l.strength} · {l.quantity} units</li>)}</ul>{o.address&&<p className="mt-3">{o.address.street}, {o.address.locality}, {o.address.city} · {o.address.pin} · {o.address.contactPhone}</p>}{!o.sharing?<p>Sharing withdrawn; patient details are unavailable.</p>:<MedicineOrderActions id={o.id} revision={o.revision} state={o.state} role={o.role}/>}<p className="mt-3">Invoice: {o.invoice_state}</p>{o.role==='PHARMACIST'&&o.invoice_state==='UNPAID'&&<BillingForm id={o.invoice_id} amount={o.total_paise}/>}</article>)}</section></>}</main>}
