import 'server-only'
import {randomUUID,createHash} from 'node:crypto'
import {ensureSchema,getDb} from '@/lib/db/client'
import {encryptSecret,decryptSecret} from '@/lib/secrets'
import {boundedText,reject} from './errors'
import {adminAccess} from './governance'
import {patientRecords} from './clinical'
export async function requestIntegrationCase(userId:string,input:{provider:string;bookingId?:string;detail:string;reference:string;key:string;consent:boolean}){
 if(!['ABDM','INSURANCE','FINANCE'].includes(input.provider)||!input.consent)reject('CONSENT','Choose a service and explicitly consent to review of your request.',400)
 const detail=boundedText(input.detail,3000,10),reference=boundedText(input.reference,300),key=boundedText(input.key,128,16),hash=createHash('sha256').update(JSON.stringify([input.provider,input.bookingId??null,detail,reference])).digest('hex')
 await ensureSchema();return getDb().transaction(async tx=>{if(!await tx.one("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[userId]))reject('FORBIDDEN','An active account is required.',403);if(input.bookingId){const b=await tx.one<{pet_id:string|null}>('SELECT pet_id FROM patient.bookings WHERE id=$1 AND user_id=$2',[input.bookingId,userId]);if(!b)reject('BOOKING','Choose your own appointment.',403);if(input.provider==='ABDM'&&b.pet_id)reject('SUBJECT','Human health ID services cannot contain veterinary records.',400)}const old=await tx.one<{id:string;encrypted_payload:string}>('SELECT id,encrypted_payload FROM integration_cases WHERE user_id=$1 AND provider=$2 AND request_key=$3',[userId,input.provider,key]);if(old){if(JSON.parse(decryptSecret(old.encrypted_payload,'integration:'+old.id)).hash!==hash)reject('IDEMPOTENCY','This request contains different details.');return old.id}const id='integration_'+randomUUID(),consent='cns_'+randomUUID();await tx.query("INSERT INTO patient.consents(id,actor_id,purpose,subject_id,version) VALUES($1,$2,'partner-case',$3,'partner-case-v1')",[consent,userId,id]);await tx.query("INSERT INTO integration_cases(id,user_id,booking_id,provider,state,encrypted_payload,consent_id,request_key) VALUES($1,$2,$3,$4,'WAITING_PARTNER',$5,$6,$7)",[id,userId,input.bookingId??null,input.provider,encryptSecret(JSON.stringify({detail,reference,hash}),'integration:'+id),consent,key]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'integration:request',$2)",[userId,id]);return id})
}
export async function integrationCases(actorId:string,admin=false){await ensureSchema();return getDb().transaction(async tx=>{if(admin)await adminAccess(tx,actorId);const rows=await tx.query<{id:string;provider:string;state:string;revision:number;encrypted_payload:string;created_at:string;consent_id:string}>("SELECT i.* FROM integration_cases i WHERE ($2::boolean OR i.user_id=$1) AND (NOT $2::boolean OR EXISTS(SELECT 1 FROM patient.consents c JOIN patient.users u ON u.id=c.actor_id WHERE c.id=i.consent_id AND c.revoked_at IS NULL AND u.status='ACTIVE')) ORDER BY i.created_at DESC LIMIT 100",[actorId,admin]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'integration:read',$1)",[actorId]);return rows.map(({encrypted_payload,...r})=>{const {hash,...payload}=JSON.parse(decryptSecret(encrypted_payload,'integration:'+r.id));return {...r,payload:payload as {detail:string;reference:string;review?:string}}})})}
export async function reviewIntegrationCase(adminId:string,id:string,revision:number,state:string,evidence:string){if(!['IN_REVIEW','NEEDS_INFORMATION','CLOSED'].includes(state))reject('STATE','Use an intake review state; live approval is not available without an onboarded partner.',400);boundedText(evidence,3000,10);await ensureSchema();await getDb().transaction(async tx=>{await adminAccess(tx,adminId);const r=await tx.one<{encrypted_payload:string;revision:number;state:string;user_id:string}>("SELECT i.* FROM integration_cases i JOIN patient.consents c ON c.id=i.consent_id JOIN patient.users u ON u.id=i.user_id WHERE i.id=$1 AND c.revoked_at IS NULL AND u.status='ACTIVE' FOR UPDATE OF i",[id]);if(!r||r.revision!==revision||r.state==='CLOSED')reject('STATE','This request changed or sharing is unavailable.');const payload=JSON.parse(decryptSecret(r.encrypted_payload,'integration:'+id));await tx.query('UPDATE integration_cases SET state=$2,revision=revision+1,encrypted_payload=$3 WHERE id=$1',[id,state,encryptSecret(JSON.stringify({...payload,review:evidence}),'integration:'+id)]);await tx.query("INSERT INTO audit_log(actor_id,action,resource,detail) VALUES($1,'integration:review',$2,$3::jsonb)",[adminId,id,JSON.stringify({state})])})}
export async function exportHumanRecordBundle(userId:string,caseId:string){
 await ensureSchema();const c=await getDb().one<{id:string}>("SELECT i.id FROM integration_cases i JOIN patient.consents c ON c.id=i.consent_id WHERE i.id=$1 AND i.user_id=$2 AND i.provider='ABDM' AND i.state<>'CLOSED' AND c.revoked_at IS NULL",[caseId,userId]);if(!c)reject('CONSENT','Create an owned human health interoperability request with current consent first.',403)
 const records=(await patientRecords(userId,{all:true})).filter(r=>r.body.subjectKind==='human'),entries=[] as {fullUrl:string;resource:Record<string,unknown>}[],patients=new Set<string>(),doctors=new Set<string>()
 for(const r of records){const b=r.body,patient='urn:carenest:patient:'+String(b.subjectId??b.patientId),doctor='urn:carenest:practitioner:'+String(b.doctorId);if(!patients.has(patient)){patients.add(patient);entries.push({fullUrl:patient,resource:{resourceType:'Patient',identifier:[{system:'urn:carenest:local-subject',value:String(b.subjectId??b.patientId)}],name:[{text:String(b.patientName??'')} ]}})}if(!doctors.has(doctor)){doctors.add(doctor);entries.push({fullUrl:doctor,resource:{resourceType:'Practitioner',identifier:[{system:'urn:carenest:local-provider',value:String(b.doctorId)}],name:[{text:String(b.doctorName??'')} ]}})}entries.push({fullUrl:'urn:carenest:document:'+r.id,resource:{resourceType:'DocumentReference',status:'current',subject:{reference:patient},author:[{reference:doctor}],date:r.created_at,description:r.collection,content:[{attachment:{contentType:'application/json',data:Buffer.from(JSON.stringify(b)).toString('base64'),title:'CareNest signed source record'}}]}})}
 await getDb().query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'integration:human-fhir-export',$2)",[userId,caseId]);return {resourceType:'Bundle',type:'collection',timestamp:new Date().toISOString(),identifier:{system:'urn:carenest:local-export',value:caseId},entry:entries}
 // Generic FHIR R4 source export only. It is not an ABDM profile certification, ABHA creation or gateway submission.
}
