import 'server-only'
import {randomBytes,randomUUID,createHash} from 'node:crypto'
import {getDb,ensureSchema} from '@/lib/db/client'
import {tokenHash,encryptSecret,localMode} from '@/lib/secrets'
import {boundedText,reject} from './errors'
import {consumeLimits} from './rate-limit'
import {requestAppointment,cancelAppointment} from './bookings'
import {ownedPets} from './pets'
import {patientRecords} from './clinical'
export async function pairMobile(userId:string){await ensureSchema();const code=randomBytes(32).toString('base64url');await getDb().transaction(async tx=>{if(!await tx.one("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE' AND role='patient' FOR UPDATE",[userId]))reject('FORBIDDEN','Mobile pairing is currently for patient accounts.',403);if(!await consumeLimits([{bucket:'mobile-pair-create',key:userId,limit:5,seconds:3600}],tx).then(r=>r.allowed))reject('RATE_LIMIT','Too many pairing requests.',429);await tx.query('DELETE FROM mobile_pairings WHERE user_id=$1',[userId]);await tx.query("INSERT INTO mobile_pairings(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '5 minutes')",[tokenHash(code),userId]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'mobile:pair-create',$1)",[userId])});return code}
export async function exchangeMobilePairing(code:string){
 if(!/^[A-Za-z0-9_-]{43}$/.test(code))reject('PAIRING','Check the private pairing code.',400)
 await ensureSchema();if(!await consumeLimits([{bucket:'mobile-pair-exchange',key:'global',limit:60,seconds:3600}]).then(r=>r.allowed))reject('RATE_LIMIT','Pairing budget exhausted.',429)
 const token=randomBytes(32).toString('base64url'),id='device_'+randomUUID()
 return getDb().transaction(async tx=>{const p=await tx.one<{user_id:string}>("UPDATE mobile_pairings SET consumed_at=now() WHERE token_hash=$1 AND consumed_at IS NULL AND expires_at>now() AND EXISTS(SELECT 1 FROM patient.users u WHERE u.id=mobile_pairings.user_id AND u.status='ACTIVE' AND u.role='patient') RETURNING user_id",[tokenHash(code)]);if(!p)reject('PAIRING','Pairing expired or was already used.',401);const u=await tx.one('SELECT id FROM patient.users WHERE id=$1 FOR UPDATE',[p.user_id]);if(!u)reject('PAIRING','Account unavailable.',401);const count=await tx.one<{n:string}>('SELECT count(*) n FROM mobile_devices WHERE user_id=$1 AND revoked_at IS NULL AND expires_at>now()',[p.user_id]);if(Number(count?.n)>=5)reject('DEVICES','Revoke an old mobile device before pairing another.');const device=await tx.one<{expires_at:string}>("INSERT INTO mobile_devices(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,now()+interval '7 days') RETURNING expires_at",[id,p.user_id,tokenHash(token)]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'mobile:pair-complete',$2)",[p.user_id,id]);return {token,deviceId:id,userId:p.user_id,expiresAt:device!.expires_at}})
}
export async function mobileActor(request:Request,write=false){const auth=request.headers.get('authorization')??'';if(!/^Bearer [A-Za-z0-9_-]{43}$/.test(auth))reject('AUTH','Pair and sign in again.',401);await ensureSchema();const d=await getDb().one<{id:string;user_id:string}>("UPDATE mobile_devices d SET last_seen_at=now() FROM patient.users u WHERE d.token_hash=$1 AND d.revoked_at IS NULL AND d.expires_at>now() AND u.id=d.user_id AND u.status='ACTIVE' AND u.role='patient' RETURNING d.id,d.user_id",[tokenHash(auth.slice(7))]);if(!d)reject('AUTH','This device session expired or was revoked.',401);const budget=await consumeLimits([{bucket:write?'mobile-write':'mobile-read',key:d.user_id,limit:write?20:120,seconds:60}]);if(!budget.allowed)reject('RATE_LIMIT','Wait before making another mobile request.',429);return d}
export async function mobileDevices(userId:string){await ensureSchema();return getDb().query<{id:string;expires_at:string;last_seen_at:string;revoked_at:string|null}>('SELECT id,expires_at,last_seen_at,revoked_at FROM mobile_devices WHERE user_id=$1 ORDER BY created_at DESC',[userId])}
export async function revokeMobileDevice(userId:string,id:string){await ensureSchema();const r=await getDb().one('UPDATE mobile_devices SET revoked_at=coalesce(revoked_at,now()) WHERE user_id=$1 AND id=$2 RETURNING id',[userId,id]);if(!r)reject('NOT_FOUND','Device unavailable.',404);await getDb().query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'mobile:revoke',$2)",[userId,id])}
export async function mobileSnapshot(userId:string){const db=getDb();const user=await db.one<{name:string}>('SELECT name FROM patient.users WHERE id=$1',[userId]),pets=await ownedPets(userId),records=await patientRecords(userId),appointments=await db.query<{id:string;doctor_name:string;starts_at:string;ends_at:string;status:string;kind:string;revision:number;payment_required:boolean}>(`SELECT b.id,d.name doctor_name,b.starts_at,b.ends_at,b.status,b.kind,b.revision,b.payment_required FROM patient.bookings b JOIN provider.doctors d ON d.id=b.doctor_id WHERE b.user_id=$1 ORDER BY b.starts_at DESC LIMIT 100`,[userId]);const slots=await db.query<{slot_id:string;doctor_id:string;name:string;speciality:string;kind:string;fee_paise:string;slot_start:string;slot_end:string}>(`SELECT s.slot_id,s.doctor_id,d.name,d.speciality,d.kind,d.fee_paise,s.slot_start,s.slot_end FROM provider.appointment_slots s JOIN provider.doctors d ON d.id=s.doctor_id JOIN patient.users u ON u.id=d.user_id LEFT JOIN clinic.clinics c ON c.id=d.clinic_id WHERE s.status='AVAILABLE' AND s.slot_start>now() AND (s.locked_until IS NULL OR s.locked_until<=now()) AND d.status='ACTIVE' AND u.status='ACTIVE' AND u.role='doctor' AND u.kyc_level='verified' AND (d.verified_at IS NOT NULL OR ($1::boolean AND d.is_demo)) AND (d.clinic_id IS NULL OR c.status='ACTIVE') ORDER BY s.slot_start LIMIT 100`,[localMode()]);return {userId,name:user?.name??'Patient',pets,appointments,records,slots,serverTime:new Date().toISOString()}}
export async function syncMobileIntent(userId:string,raw:Record<string,unknown>){
 const key=boundedText(raw.key,128,16),kind=String(raw.kind),payload=raw.payload as Record<string,unknown>;if(!payload||typeof payload!=='object'||Array.isArray(payload)||!['BOOK','CANCEL'].includes(kind))reject('INTENT','Choose an explicitly supported operation.',400)
 const canonical=kind==='BOOK'?{doctorId:String(payload.doctorId??''),slotId:String(payload.slotId??''),petId:typeof payload.petId==='string'?payload.petId:null,consent:payload.consent===true}:{bookingId:String(payload.bookingId??''),revision:Number(payload.revision)}
 const hash=createHash('sha256').update(JSON.stringify([kind,canonical])).digest('hex');await ensureSchema()
 const prior=await getDb().transaction(async tx=>{await tx.query("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[userId]);await tx.query('INSERT INTO mobile_sync_intents(user_id,intent_key,payload_hash) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[userId,key,hash]);const p=await tx.one<{payload_hash:string;result:Record<string,unknown>|null}>('SELECT payload_hash,result FROM mobile_sync_intents WHERE user_id=$1 AND intent_key=$2',[userId,key]);if(p!.payload_hash!==hash)reject('IDEMPOTENCY','This offline intent contains different details.');return p!.result})
 if(prior)return prior
 let result:Record<string,unknown>
 if(kind==='BOOK'){const p=canonical as {doctorId:string;slotId:string;petId:string|null;consent:boolean};const b=await requestAppointment({actorId:userId,doctorId:p.doctorId,slotId:p.slotId,petId:p.petId,mode:'clinic',consent:p.consent,idempotencyKey:key,paymentRequired:true});result={bookingId:b.id,state:b.status==='confirmed'?'CONFIRMED':'AWAITING_PAYMENT',checkoutPath:'/account/checkout/'+encodeURIComponent(b.id)}}
 else{const p=canonical as {bookingId:string;revision:number};if(!Number.isInteger(p.revision)||p.revision<0)reject('REVISION','A current appointment revision is required.',400);await cancelAppointment(userId,p.bookingId,p.revision);result={bookingId:p.bookingId,state:'CANCELLED'}}
 await getDb().query('UPDATE mobile_sync_intents SET result=$3::jsonb WHERE user_id=$1 AND intent_key=$2',[userId,key,JSON.stringify(result)])
 // Intents are not confirmations. The server's reservation and current revision remain authoritative.
 await getDb().query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'mobile:sync',$2)",[userId,key]);return result
}
