import 'server-only'
import {randomUUID,createHash} from 'node:crypto'
import {getDb,ensureSchema,type Db} from '@/lib/db/client'
import {encryptSecret,decryptSecret,localMode} from '@/lib/secrets'
import {paise} from '@/lib/money'
import {boundedText,reject} from './errors'
import {adminAccess} from './governance'
import {homeAddressSnapshot} from './home-visits'
import {encounter,decodeRecord} from './clinical'
import {activeDoctor} from './clinic-access'
type Prescription={id:string;encounter_id:string;clinician_id:string;owner_id:string|null;body:Record<string,unknown>;created_at:string;kind:string;species:string|null}
async function ownedPrescription(tx:Db,actorId:string,id:string){const r=await tx.one<Prescription&{person_identity:string|null;clinic_person_id:string|null}>(`SELECT d.*,b.kind,p.species,cp.encrypted_identity person_identity,e.clinic_person_id FROM documents d JOIN clinic.encounters e ON e.id=d.encounter_id LEFT JOIN patient.bookings b ON b.id=e.booking_id LEFT JOIN patient.pets p ON p.id=e.pet_id LEFT JOIN clinic.people cp ON cp.id=e.clinic_person_id WHERE d.id=$1 AND d.collection='prescriptions' AND (d.owner_id=$2 OR (d.owner_id IS NULL AND e.patient_user_id=$2))`,[id,actorId]);if(!r)reject('PRESCRIPTION','Choose an owned signed prescription.',403);const {person_identity,clinic_person_id,...record}=r;return {...record,species:r.species??(person_identity&&clinic_person_id?String(JSON.parse(decryptSecret(person_identity,'person:'+clinic_person_id)).species??'other'):null),body:decodeRecord(r.id,r.body)}}
async function pharmacyStaff(tx:Db,actorId:string,partnerId:string,roles:string[]){
 const m=await tx.one<{role:string}>(`SELECT m.role FROM pharmacy.memberships m JOIN pharmacy.partners p ON p.id=m.partner_id JOIN clinic.clinics c ON c.id=p.clinic_id JOIN patient.users u ON u.id=m.user_id WHERE m.user_id=$1 AND m.partner_id=$2 AND m.status='ACTIVE' AND u.status='ACTIVE' AND p.status='ACTIVE' AND p.verified_at IS NOT NULL AND c.status='ACTIVE' AND p.expires_on>=(now() AT TIME ZONE 'Asia/Kolkata')::date AND (m.role<>'PHARMACIST' OR m.verified_at IS NOT NULL) FOR SHARE OF m,p,c,u`,[actorId,partnerId])
 if(!m||!roles.includes(m.role))reject('FORBIDDEN','Current licensed pharmacy assignment is required.',403)
 return m
}
export async function publishMedicine(adminId:string,raw:Record<string,unknown>){
 const name=boundedText(raw.name,120,2),strength=boundedText(raw.strength,120,1),form=boundedText(raw.form,80,2),species=Array.isArray(raw.species)?raw.species.map(String):[],restrictions=raw.restrictions??{}
 if(!species.length||species.some(s=>!['human','dog','cat','rabbit','bird','other'].includes(s))||!restrictions||typeof restrictions!=='object')reject('CATALOGUE','Provide explicit supported species and reviewed restrictions.',400)
 await ensureSchema();const policy=await getDb().one<{id:string}>("SELECT id FROM review_policies WHERE kind='PRESCRIBING' AND state='APPROVED' AND content->'species' @> $1::jsonb AND ($2::boolean OR coalesce((content->>'demo')::boolean,false)=false) ORDER BY version DESC LIMIT 1",[JSON.stringify(species),localMode()]);if(!policy)reject('POLICY','Approve an actual professionally reviewed prescribing policy covering every selected species first.')
 await ensureSchema();return getDb().transaction(async tx=>{await adminAccess(tx,adminId);const id='med_'+randomUUID();await tx.query("INSERT INTO clinical_catalogue(id,name,strength,form,species,policy_id,restrictions,status) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,'ACTIVE')",[id,name,strength,form,species,policy.id,JSON.stringify(restrictions)]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'catalogue:publish',$2)",[adminId,id]);return id})
}
export async function recordPrescriptionSafety(actorId:string,recordId:string,decision:string,detail:string){
 if(!['APPROVED','REJECTED','NEEDS_CLARIFICATION'].includes(decision))reject('DECISION','Choose a professional review decision.',400);boundedText(detail,2000,20)
 await ensureSchema();return getDb().transaction(async tx=>{const r=await tx.one<{encounter_id:string;clinician_id:string}>('SELECT encounter_id,clinician_id FROM documents WHERE id=$1 AND collection=\'prescriptions\'',[recordId]);if(!r)reject('PRESCRIPTION','Prescription unavailable.',404);const d=await activeDoctor(tx,r.clinician_id);if(d.user_id!==actorId)reject('FORBIDDEN','The assigned prescriber must record this clinical safety review.',403);await encounter(tx,actorId,r.encounter_id,true);const id='safety_'+randomUUID();await tx.query('INSERT INTO prescription_safety_reviews(id,record_id,reviewer_id,decision,encrypted_detail) VALUES($1,$2,$3,$4,$5) ON CONFLICT(record_id,reviewer_id) DO UPDATE SET decision=$4,encrypted_detail=$5,created_at=now()',[id,recordId,actorId,decision,encryptSecret(detail,'safety:'+recordId+':'+actorId)]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'prescription:safety-review',$2)",[actorId,recordId])})
}
export async function publishPharmacy(adminId:string,input:{clinicId:string;name:string;registration:string;expiresOn:string;userId:string;professionalReference:string;checked:boolean}){
 if(!input.checked||!/^\d{4}-\d{2}-\d{2}$/.test(input.expiresOn)||new Date(input.expiresOn)<new Date())reject('LICENSE','Record actual current pharmacy and pharmacist licence checks.',400)
 boundedText(input.name,120,2);boundedText(input.registration,150,3);boundedText(input.professionalReference,200,10)
 await ensureSchema();return getDb().transaction(async tx=>{await adminAccess(tx,adminId);if(!await tx.one("SELECT id FROM clinic.clinics WHERE id=$1 AND status='ACTIVE'",[input.clinicId])||!await tx.one("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE'",[input.userId]))reject('PARTNER','An active clinic and actual operator account are required.');const id='pharm_'+randomUUID();await tx.query("INSERT INTO pharmacy.partners(id,clinic_id,name,registration,status,verified_by,verified_at,expires_on) VALUES($1,$2,$3,$4,'ACTIVE',$5,now(),$6)",[id,input.clinicId,input.name,input.registration,adminId,input.expiresOn]);await tx.query("INSERT INTO pharmacy.memberships(partner_id,user_id,role,professional_reference,verified_at) VALUES($1,$2,'PHARMACIST',$3,now())",[id,input.userId,input.professionalReference]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'pharmacy:verify',$2)",[adminId,id]);return id})
}
export async function setInventory(actorId:string,partnerId:string,medicineId:string,stock:number,price:string){
 const amount=paise(price).toString();if(!Number.isInteger(stock)||stock<0||stock>1000000)reject('STOCK','Enter a valid available stock count.',400)
 await ensureSchema();await getDb().transaction(async tx=>{await pharmacyStaff(tx,actorId,partnerId,['PHARMACIST']);if(!await tx.one("SELECT id FROM clinical_catalogue WHERE id=$1 AND status='ACTIVE'",[medicineId]))reject('CATALOGUE','The medicine must be professionally reviewed and published.');const prior=await tx.one<{reserved:number}>('SELECT reserved FROM pharmacy.inventory WHERE partner_id=$1 AND catalogue_id=$2 FOR UPDATE',[partnerId,medicineId]);if(prior&&stock<prior.reserved)reject('STOCK','Stock cannot fall below already reserved units.');await tx.query('INSERT INTO pharmacy.inventory(partner_id,catalogue_id,stock,price_paise) VALUES($1,$2,$3,$4) ON CONFLICT(partner_id,catalogue_id) DO UPDATE SET stock=$3,price_paise=$4,revision=pharmacy.inventory.revision+1',[partnerId,medicineId,stock,amount]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'pharmacy:inventory',$2)",[actorId,partnerId])})
}
export async function pharmacyCatalogue(){await ensureSchema();return getDb().query<{partner_id:string;partner_name:string;id:string;name:string;strength:string;form:string;price_paise:string;available:number;species:string[]}>(`SELECT p.id partner_id,p.name partner_name,m.id,m.name,m.strength,m.form,m.species,i.price_paise,i.stock-i.reserved available FROM pharmacy.partners p JOIN clinic.clinics c ON c.id=p.clinic_id JOIN pharmacy.inventory i ON i.partner_id=p.id JOIN clinical_catalogue m ON m.id=i.catalogue_id JOIN review_policies policy ON policy.id=m.policy_id WHERE p.status='ACTIVE' AND p.verified_at IS NOT NULL AND c.status='ACTIVE' AND p.expires_on>=(now() AT TIME ZONE 'Asia/Kolkata')::date AND m.status='ACTIVE' AND policy.state='APPROVED' AND ($1::boolean OR coalesce((policy.content->>'demo')::boolean,false)=false) ORDER BY p.name,m.name LIMIT 200`,[localMode()])}
export async function requestMedicineOrder(actorId:string,input:{partnerId:string;prescriptionId:string;addressId:string;requestKey:string;lines:{medicineId:string;quantity:number}[];consent:boolean}){
 boundedText(input.requestKey,128,16);if(!input.consent||!Array.isArray(input.lines)||input.lines.length<1||input.lines.length>20)reject('ORDER','Select medicines from your actual prescription and give pharmacy-sharing consent.',400)
 if(new Set(input.lines.map(l=>l.medicineId)).size!==input.lines.length||input.lines.some(l=>!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>100))reject('QUANTITY','Check the requested quantities.',400)
 await ensureSchema();return getDb().transaction(async tx=>{
  if(!await tx.one("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[actorId]))reject('FORBIDDEN','An active account is required.',403)
  const requestHash=createHash('sha256').update(JSON.stringify([input.partnerId,input.prescriptionId,input.addressId,[...input.lines].sort((a,b)=>a.medicineId.localeCompare(b.medicineId))])).digest('hex'); const prior=await tx.one<{id:string;prescription_id:string;partner_id:string;request_hash:string}>('SELECT id,prescription_id,partner_id,request_hash FROM pharmacy.orders WHERE user_id=$1 AND request_key=$2',[actorId,input.requestKey]);if(prior){if(prior.request_hash!==requestHash)reject('IDEMPOTENCY','The intent identifies another medicine request.');return prior.id}
  const prescription=await ownedPrescription(tx,actorId,input.prescriptionId),address=await homeAddressSnapshot(tx,actorId,input.addressId)
  if(!await tx.one("SELECT p.id FROM pharmacy.partners p JOIN clinic.clinics c ON c.id=p.clinic_id WHERE p.id=$1 AND p.status='ACTIVE' AND p.verified_at IS NOT NULL AND c.status='ACTIVE' AND p.expires_on>=(now() AT TIME ZONE 'Asia/Kolkata')::date",[input.partnerId]))reject('PARTNER','The selected pharmacy is not currently verified.')
  let total=0n;const id='order_'+randomUUID(),lines=[]
  for(const line of [...input.lines].sort((a,b)=>a.medicineId.localeCompare(b.medicineId))){const m=await tx.one<{name:string;price_paise:string;species:string[];restrictions:Record<string,unknown>}>('SELECT m.name,m.species,m.restrictions,i.price_paise FROM pharmacy.inventory i JOIN clinical_catalogue m ON m.id=i.catalogue_id JOIN review_policies p ON p.id=m.policy_id WHERE i.partner_id=$1 AND i.catalogue_id=$2 AND m.status=\'ACTIVE\' AND p.state=\'APPROVED\' AND ($3::boolean OR coalesce((p.content->>\'demo\')::boolean,false)=false) FOR SHARE OF i,m,p',[input.partnerId,line.medicineId,localMode()]);if(!m)reject('MEDICINE','The selected medicine is not currently published.');const drugs=prescription.body.drugs as {drug:string}[];if(!Array.isArray(drugs)||!drugs.some(d=>d.drug.trim().toLocaleLowerCase()===m.name.trim().toLocaleLowerCase()))reject('PRESCRIPTION','A requested medicine does not match the prescription; seek prescriber clarification.');if(!m.species.includes(prescription.body.subjectKind==='pet'?prescription.species??'other':'human'))reject('SPECIES','The reviewed catalogue does not support this care subject.');if(m.restrictions.inPersonOnly===true||m.restrictions.deliveryAllowed!==true)reject('RESTRICTION','This medicine requires direct professional arrangements.');total+=paise(m.price_paise)*BigInt(line.quantity);lines.push({...line,price:m.price_paise})}
  await tx.query('INSERT INTO pharmacy.orders(id,user_id,partner_id,prescription_id,address_id,encrypted_address,total_paise,request_key,request_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,actorId,input.partnerId,prescription.id,input.addressId,encryptSecret(JSON.stringify(address),'pharmacy-address:'+id),total.toString(),input.requestKey,requestHash])
  for(const line of lines)await tx.query('INSERT INTO pharmacy.order_lines(order_id,catalogue_id,quantity,price_paise) VALUES($1,$2,$3,$4)',[id,line.medicineId,line.quantity,line.price])
  await tx.query('INSERT INTO clinic.invoices(id,user_id,pharmacy_order_id,total_paise) VALUES($1,$2,$3,$4)',['inv_'+randomUUID(),actorId,id,total.toString()])
  await tx.query("INSERT INTO patient.consents(id,actor_id,purpose,subject_id,version) VALUES($1,$2,'pharmacy-sharing',$3,'pharmacy-v1')",['cns_'+randomUUID(),actorId,id]);await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'pharmacy:request',$2)",[actorId,id]);return id
 })
}
export async function transitionMedicineOrder(actorId:string,id:string,revision:number,next:string,reference=''){
 const transitions:Record<string,string[]>={REQUESTED:['APPROVED','REJECTED'],APPROVED:['PACKED','CANCELLED'],PACKED:['DISPATCHED','CANCELLED'],DISPATCHED:['DELIVERED']}
 await ensureSchema();return getDb().transaction(async tx=>{
  const order=await tx.one<{user_id:string;partner_id:string;prescription_id:string;state:string;revision:number}>('SELECT * FROM pharmacy.orders WHERE id=$1 FOR UPDATE',[id]);if(!order)reject('NOT_FOUND','Order unavailable.',404)
  await pharmacyStaff(tx,actorId,order.partner_id,next==='DELIVERED'||next==='DISPATCHED'?['PHARMACIST','DISPATCH']:['PHARMACIST'])
  if(order.revision!==revision||!transitions[order.state]?.includes(next))reject('STATE','This order changed or transition is unavailable.')
  if(!await tx.one("SELECT id FROM patient.users WHERE id=$1 AND status='ACTIVE'",[order.user_id])||!await tx.one("SELECT id FROM patient.consents WHERE actor_id=$1 AND subject_id=$2 AND purpose='pharmacy-sharing' AND revoked_at IS NULL",[order.user_id,id]))reject('CONSENT','Current customer access and sharing consent are required.')
  const lines=await tx.query<{catalogue_id:string;quantity:number}>('SELECT catalogue_id,quantity FROM pharmacy.order_lines WHERE order_id=$1 ORDER BY catalogue_id',[id])
  if(next==='DISPATCHED'&&!await tx.one("SELECT id FROM clinic.invoices WHERE pharmacy_order_id=$1 AND state IN ('PAID','WAIVED')",[id]))reject('PAYMENT','Record a verified invoice payment before dispatch; payment promises do not settle an invoice.')
  if(next==='APPROVED'){
   const prescription=await ownedPrescription(tx,order.user_id,order.prescription_id);await activeDoctor(tx,prescription.clinician_id)
   if(await tx.one('SELECT id FROM documents WHERE supersedes=$1',[prescription.id]))reject('AMENDED','This prescription was amended. Ask the customer to place a request against the current signed record.')
   const prescriber=await activeDoctor(tx,prescription.clinician_id)
   if(!await tx.one("SELECT id FROM prescription_safety_reviews WHERE record_id=$1 AND reviewer_id=$2 AND decision='APPROVED'",[prescription.id,prescriber.user_id]))reject('SAFETY','The current prescriber must document the clinical safety review before dispensing.')
   for(const line of lines)if(!await tx.one("SELECT m.id FROM clinical_catalogue m JOIN review_policies p ON p.id=m.policy_id WHERE m.id=$1 AND m.status='ACTIVE' AND p.state='APPROVED' AND ($2::boolean OR coalesce((p.content->>'demo')::boolean,false)=false)",[line.catalogue_id,localMode()]))reject('POLICY','A catalogue entry or its prescribing policy is no longer active.')
   for(const line of lines){const stock=await tx.one('UPDATE pharmacy.inventory SET reserved=reserved+$3,revision=revision+1 WHERE partner_id=$1 AND catalogue_id=$2 AND stock-reserved>=$3 RETURNING catalogue_id',[order.partner_id,line.catalogue_id,line.quantity]);if(!stock)reject('STOCK','A medicine is out of stock; existing reservations are unchanged.')}
  }
  if(['CANCELLED','REJECTED'].includes(next)){if(order.state!=='REQUESTED')for(const line of lines)await tx.query('UPDATE pharmacy.inventory SET reserved=reserved-$3 WHERE partner_id=$1 AND catalogue_id=$2 AND reserved>=$3',[order.partner_id,line.catalogue_id,line.quantity]);await tx.query("UPDATE clinic.invoices SET state='VOID' WHERE pharmacy_order_id=$1 AND state='UNPAID'",[id])}
  if(next==='DELIVERED'){boundedText(reference,300,5);for(const line of lines)await tx.query('UPDATE pharmacy.inventory SET stock=stock-$3,reserved=reserved-$3 WHERE partner_id=$1 AND catalogue_id=$2 AND reserved>=$3',[order.partner_id,line.catalogue_id,line.quantity])}
  await tx.query('UPDATE pharmacy.orders SET state=$2,revision=revision+1,reviewed_by=CASE WHEN $2=\'APPROVED\' THEN $3 ELSE reviewed_by END,reviewed_at=CASE WHEN $2=\'APPROVED\' THEN now() ELSE reviewed_at END WHERE id=$1',[id,next,actorId])
  if(next==='DISPATCHED'||next==='DELIVERED')await tx.query('INSERT INTO pharmacy.fulfilments(order_id,assigned_to,tracking_ref,delivered_at,encrypted_receipt) VALUES($1,$2,$3,CASE WHEN $4=\'DELIVERED\' THEN now() ELSE NULL END,$5) ON CONFLICT(order_id) DO UPDATE SET tracking_ref=$3,delivered_at=CASE WHEN $4=\'DELIVERED\' THEN now() ELSE pharmacy.fulfilments.delivered_at END,encrypted_receipt=$5',[id,actorId,reference.slice(0,300),next,encryptSecret(reference,'pharmacy-receipt:'+id)])
  await tx.query("INSERT INTO audit_log(actor_id,action,resource,detail) VALUES($1,'pharmacy:transition',$2,$3::jsonb)",[actorId,id,JSON.stringify({from:order.state,to:next})]);await tx.query("INSERT INTO domain_events(kind,subject_id,payload,event_key) VALUES('pharmacy.updated',$1,$2::jsonb,$3)",[id,JSON.stringify({userId:order.user_id}),'pharmacy:'+id+':'+(revision+1)])
 })
}
export async function ownMedicineOrders(actorId:string){await ensureSchema();return getDb().query<{id:string;state:string;total_paise:string;partner_name:string}>('SELECT o.*,p.name partner_name FROM pharmacy.orders o JOIN pharmacy.partners p ON p.id=o.partner_id WHERE o.user_id=$1 ORDER BY o.created_at DESC LIMIT 100',[actorId])}
export async function pharmacyWork(actorId:string){
 await ensureSchema();return getDb().transaction(async tx=>{
  const partners=await tx.query<{id:string;name:string;role:string}>(`SELECT p.id,p.name,m.role FROM pharmacy.partners p JOIN pharmacy.memberships m ON m.partner_id=p.id JOIN patient.users u ON u.id=m.user_id JOIN clinic.clinics c ON c.id=p.clinic_id WHERE m.user_id=$1 AND m.status='ACTIVE' AND p.status='ACTIVE' AND p.verified_at IS NOT NULL AND u.status='ACTIVE' AND c.status='ACTIVE' AND p.expires_on>=(now() AT TIME ZONE 'Asia/Kolkata')::date`,[actorId])
  const orders=[]
  for(const p of partners){
   await pharmacyStaff(tx,actorId,p.id,['PHARMACIST','DISPATCH'])
   const rows=await tx.query<{id:string;state:string;revision:number;prescription_id:string;user_id:string;encrypted_address:string;total_paise:string;invoice_id:string;invoice_state:string}>(`SELECT o.*,i.id invoice_id,i.state invoice_state FROM pharmacy.orders o JOIN clinic.invoices i ON i.pharmacy_order_id=o.id WHERE o.partner_id=$1 ORDER BY o.created_at DESC LIMIT 100`,[p.id])
   for(const r of rows){
    const sharing=Boolean(await tx.one("SELECT c.id FROM patient.consents c JOIN patient.users u ON u.id=c.actor_id WHERE c.actor_id=$1 AND c.subject_id=$2 AND c.purpose='pharmacy-sharing' AND c.revoked_at IS NULL AND u.status='ACTIVE' FOR SHARE OF c,u",[r.user_id,r.id]))
    const prescription=p.role==='PHARMACIST'&&sharing?await ownedPrescription(tx,r.user_id,r.prescription_id):null
    const {encrypted_address,...row}=r
    const address=sharing&&!['CANCELLED','REJECTED','DELIVERED'].includes(r.state)?JSON.parse(decryptSecret(encrypted_address,'pharmacy-address:'+r.id)) as Record<string,string>:null
    const lines=p.role==='PHARMACIST'&&sharing?await tx.query<{name:string;strength:string;quantity:number}>(`SELECT m.name,m.strength,l.quantity FROM pharmacy.order_lines l JOIN clinical_catalogue m ON m.id=l.catalogue_id WHERE l.order_id=$1`,[r.id]):[]
    orders.push({...row,partner_name:p.name,role:p.role,prescription:prescription?.body??null,address,lines,sharing})
   }
  }
  await tx.query("INSERT INTO audit_log(actor_id,action,resource) VALUES($1,'pharmacy:read',$1)",[actorId]);return {partners,orders}
 })
}
export async function inventoryForStaff(actorId:string){const work=await pharmacyWork(actorId);const rows=[];for(const p of work.partners.filter(p=>p.role==='PHARMACIST')){const items=await getDb().query<{catalogue_id:string;name:string;stock:number;reserved:number;price_paise:string}>('SELECT i.*,m.name FROM pharmacy.inventory i JOIN clinical_catalogue m ON m.id=i.catalogue_id WHERE i.partner_id=$1 ORDER BY m.name',[p.id]);rows.push(...items.map(i=>({...i,partner_id:p.id,partner_name:p.name})))}return rows}
export async function medicineCatalogueForAdmin(adminId:string){await ensureSchema();await adminAccess(getDb(),adminId);return getDb().query<{id:string;name:string;strength:string;form:string;status:string;species:string[]}>('SELECT * FROM clinical_catalogue ORDER BY name LIMIT 500')}
