import 'server-only'
import {randomUUID,createHash} from 'node:crypto'
import {getDb,ensureSchema} from '@/lib/db/client'
import {encryptSecret,decryptSecret} from '@/lib/secrets'
import {adminAccess} from './governance'
import {reject,boundedText} from './errors'
import {activeDoctor} from './clinic-access'
export async function scanLegacyDocuments(adminId:string){await ensureSchema();return getDb().transaction(async tx=>{await adminAccess(tx,adminId);const rows=await tx.query<{id:string;body:Record<string,unknown>}>('SELECT d.id,d.body FROM documents d LEFT JOIN clinic.encounters e ON e.id=d.encounter_id WHERE d.collection IN (\'prescriptions\',\'chart_notes\') AND (d.encounter_id IS NULL OR (d.owner_id IS NULL AND e.clinic_person_id IS NULL)) ORDER BY d.created_at LIMIT 1000');for(const r of rows){if(typeof r.body._encrypted!=='string')await tx.query('UPDATE documents SET body=$2::jsonb WHERE id=$1',[r.id,JSON.stringify({_encrypted:encryptSecret(JSON.stringify(r.body),'clinical:'+r.id)})]);await tx.query('INSERT INTO data_reconciliation_cases(id,document_id) VALUES($1,$2) ON CONFLICT(document_id) DO NOTHING',['reconcile_'+randomUUID(),r.id])}await tx.query("INSERT INTO audit_log(actor_id,action,resource,detail) VALUES($1,'legacy:scan','documents',$2::jsonb)",[adminId,JSON.stringify({count:rows.length})]);return rows.length})}
export async function reconciliationCases(adminId:string){await ensureSchema();await adminAccess(getDb(),adminId);return getDb().query<{id:string;document_id:string;state:string;collection:string;created_at:string}>('SELECT c.id,c.document_id,c.state,d.collection,d.created_at FROM data_reconciliation_cases c JOIN documents d ON d.id=c.document_id ORDER BY c.created_at DESC LIMIT 200')}
export async function reconcileDocument(adminId:string,id:string,encounterId:string,evidence:string,checked:boolean){if(!checked)reject('REVIEW','Actual source identity and ownership review is required.',400);boundedText(evidence,2000,20);await ensureSchema();await getDb().transaction(async tx=>{await adminAccess(tx,adminId);const r=await tx.one<{document_id:string;body:Record<string,unknown>;collection:string}>(`SELECT c.document_id,d.body,d.collection FROM data_reconciliation_cases c JOIN documents d ON d.id=c.document_id WHERE c.id=$1 AND c.state='PENDING' AND d.encounter_id IS NULL AND d.owner_id IS NULL FOR UPDATE OF c,d`,[id]);if(!r)reject('STATE','This unresolved legacy document is unavailable.');const e=await tx.one<{patient_user_id:string;family_id:string|null;pet_id:string|null;doctor_id:string}>('SELECT patient_user_id,family_id,pet_id,doctor_id FROM clinic.encounters WHERE id=$1 AND patient_user_id IS NOT NULL AND booking_id IS NOT NULL FOR SHARE',[encounterId]);if(!e)reject('ENCOUNTER','Choose an existing owned scheduled encounter; no encounter will be invented.');await activeDoctor(tx,e.doctor_id);const body=typeof r.body._encrypted==='string'?JSON.parse(decryptSecret(r.body._encrypted,'clinical:'+r.document_id)):r.body;const subject=e.pet_id??e.family_id??e.patient_user_id;if(body.patientId!==subject||body.doctorId!==e.doctor_id)reject('IDENTITY','The original subject and clinician identifiers must match the selected existing encounter. Ambiguous records remain quarantined.');const hash=createHash('sha256').update(JSON.stringify(body)).digest('hex');await tx.query('UPDATE documents SET encounter_id=$2,owner_id=$3,clinician_id=$4,body=$5::jsonb WHERE id=$1',[r.document_id,encounterId,e.patient_user_id,e.doctor_id,JSON.stringify({_encrypted:encryptSecret(JSON.stringify({...body,subjectId:subject,ownerId:e.patient_user_id,subjectKind:e.pet_id?'pet':'human',imported:true,sourceHash:hash}),'clinical:'+r.document_id)})]);await tx.query("UPDATE data_reconciliation_cases SET state='LINKED',resolved_by=$2,encrypted_reason=$3,resolved_at=now() WHERE id=$1",[id,adminId,encryptSecret(evidence,'reconcile:'+id)]);await tx.query("INSERT INTO audit_log(actor_id,action,resource,detail) VALUES($1,'legacy:link',$2,$3::jsonb)",[adminId,r.document_id,JSON.stringify({sourceHash:hash,encounterId})])})}
