import 'server-only'
import {ensureSchema,getDb} from '@/lib/db/client'
import {adminAccess,companySettings,approvedPolicy} from './governance'
import {onlinePaymentsConfigured} from './billing'
import {livekitConfigured} from './livekit'
import {localMode} from '@/lib/secrets'
import {readFile} from 'node:fs/promises'
import path from 'node:path'
export async function integrationReadiness(adminId:string){await ensureSchema();await adminAccess(getDb(),adminId);const company=await companySettings(),clinical=await approvedPolicy('CLINICAL'),privacy=await approvedPolicy('PRIVACY'),prescribing=await approvedPolicy('PRESCRIBING');let owner:string|null=null,zoomVerified=false;try{const record=JSON.parse(await readFile(path.join(process.cwd(),'.data','setup','provider-owner.json'),'utf8'));if(typeof record.ownerEmail==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(record.ownerEmail))owner=record.ownerEmail;zoomVerified=record.zoom?.accountAccessVerified===true&&record.zoom?.signInEmailMatched===true}catch{}return [
 {name:'Provider account owner',status:owner?owner+' — user supplied; possession and registrations not verified':'Owner email not supplied',next:'Keep account ownership separate from the public grievance contact. Complete owner login, provider age/identity verification and terms at their actual signup steps. No account has been registered merely by saving this address.',url:'/admin/setup'},
 {name:'Local infrastructure',status:localMode()?'Local mode; no cloud deployment':'Non-local configuration',next:'Keep local data backed up with its keys. Local mode uses console sign-in codes and blocks external notification delivery.',url:'/admin/operations'},
 {name:'LiveKit video',status:livekitConfigured()?'Local credentials configured; device call validation pending':'Local video service not configured',next:'Run npm run video:local, restart the app and test a patient/clinician call. Calls use local LiveKit; no Zoom app or cloud account is required. Phone/LAN access needs a separate secure networking setup.',url:'https://docs.livekit.io/transport/self-hosting/local/'},
 {name:'Google sign-in and Meet',status:process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET?'Application credentials present; consent and call test pending':'Not configured',next:'Create a real Google developer project and web OAuth client. Register /api/auth/google/callback and /api/integrations/google/callback for APP_ORIGIN. Enable Calendar API; complete consent and any verification. Cloud hosting migration remains disabled.',url:'https://developers.google.com/workspace/calendar/api/quickstart/js'},
 {name:'Razorpay',status:onlinePaymentsConfigured()?'Enabled test configuration; real capture/refund evidence pending':'Not configured',next:'Create your business account and complete KYC, use test keys first, configure the signed webhook, then verify capture, duplicate events, late captures and refunds before enabling live collection.',url:'https://razorpay.com/docs/payments/dashboard/account-settings/api-keys/'},
 {name:'Email and SMS',status:process.env.RESEND_API_KEY&&process.env.EMAIL_FROM?'Email credentials present; local delivery remains disabled':'Not configured',next:'Register and verify a sender/domain and actual SMS provider templates/Indian DLT requirements. User preferences default off; OTP is a separate purpose. Real delivery receipts need account testing.',url:'https://resend.com/docs/dashboard/domains/introduction'},
 {name:'Human health interoperability',status:'No registered ABDM sandbox or production partner',next:'Apply with the actual organization in the ABDM sandbox; implement against the issued current contract and validate ABDM profiles/consent flows. The local FHIR source export is not ABHA issuance, PM-JAY approval or certification.',url:'https://sandbox.abdm.gov.in/'},
 {name:'Pharmacy, insurer and finance partners',status:'Live partner authority not configured',next:'Use actual licensed pharmacy/pharmacist evidence and reviewed prescribing policy before catalogue publication. Insurance/finance requests remain intake only until approved partners and contracts are supplied.',url:'/admin/clinical'},
 {name:'Company and governance',status:company&&privacy&&clinical&&prescribing?'Operator-entered details and policy attestations recorded; independent evidence required':'Actual company details and/or professional policy approvals missing',next:'Enter the real legal entity, registration, grievance contact and documented professional/legal review. No company, licence or approval is invented.',url:'/admin/governance'}
 ]}
