import 'server-only'
import {ensureSchema,getDb} from '@/lib/db/client'
import {adminAccess,companySettings,approvedPolicy} from './governance'
import {onlinePaymentsConfigured} from './billing'
import {livekitConfigured} from './livekit'
import {localMode} from '@/lib/secrets'
import {readFile} from 'node:fs/promises'
import path from 'node:path'
import {fast2smsReady,fast2smsQuickOtp} from '@/lib/fast2sms'
import {emailConfigured} from '@/lib/email'
import {twilioVerifyConfigured} from '@/lib/twilio-verify'
import {metaWhatsAppSelected,metaWhatsAppReady} from '@/lib/meta-whatsapp'
export async function integrationReadiness(adminId:string){await ensureSchema();await adminAccess(getDb(),adminId);const company=await companySettings(),clinical=await approvedPolicy('CLINICAL'),privacy=await approvedPolicy('PRIVACY'),prescribing=await approvedPolicy('PRESCRIBING');let owner:string|null=null,zoomVerified=false;try{const record=JSON.parse(await readFile(path.join(process.cwd(),'.data','setup','provider-owner.json'),'utf8'));if(typeof record.ownerEmail==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(record.ownerEmail))owner=record.ownerEmail;zoomVerified=record.zoom?.accountAccessVerified===true&&record.zoom?.signInEmailMatched===true}catch{}return [
 {name:'Provider account owner',status:owner?owner+' — user supplied; possession and registrations not verified':'Owner email not supplied',next:'Keep account ownership separate from the public grievance contact. Complete owner login, provider age/identity verification and terms at their actual signup steps. No account has been registered merely by saving this address.',url:'/admin/setup'},
 {name:'Local infrastructure',status:localMode()?'Local mode; no cloud deployment':'Non-local configuration',next:'Keep local data backed up with its keys. Phone delivery requires an explicitly configured provider. Demo OTPs are off by default; enabling them requires both SMS_PROVIDER=console and ALLOW_LOCAL_OTP=1.',url:'/admin/operations'},
 {name:'LiveKit video',status:livekitConfigured()?'Local credentials configured; device call validation pending':'Local video service not configured',next:'Run npm run video:local, restart the app and test a patient/clinician call. Calls use local LiveKit; no Zoom app or cloud account is required. Phone/LAN access needs a separate secure networking setup.',url:'https://docs.livekit.io/transport/self-hosting/local/'},
 {name:'Google sign-in and Meet',status:process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET?'Application credentials present; consent and call test pending':'Not configured',next:'Create a real Google developer project and web OAuth client. Register /api/auth/google/callback and /api/integrations/google/callback for APP_ORIGIN. Enable Calendar API; complete consent and any verification. Cloud hosting migration remains disabled.',url:'https://developers.google.com/workspace/calendar/api/quickstart/js'},
 {name:'Cashfree sandbox',status:onlinePaymentsConfigured()?'Enabled test configuration; real capture/refund evidence pending':'Not configured',next:'Switch Cashfree to Test, save Payment Gateway sandbox credentials, then test checkout, signed webhooks and refunds. The MVP blocks production payments. Easy Split and recurring subscriptions require separate activation and integration.',url:'https://www.cashfree.com/docs/payments/online/web'},
 {name:'Booking email',status:emailConfigured()?'Sender credentials configured; inbox delivery test pending':'Sender setup pending',next:'Connect the receiving Google email to the patient account, enable email booking updates and reminders, then use Send a test email. Gmail demo sending is explicitly enabled locally and capped at ten attempts per rolling day.',url:'/account/notifications'},
 {name:'Twilio Verify SMS OTP',status:process.env.SMS_PROVIDER==='twilio-verify'?(twilioVerifyConfigured()?'Selected; provider-generated six-digit OTPs':'Selected; credentials incomplete'):'Not selected',next:'Verify the test recipient in the Twilio trial account and allow India SMS in Verify Geo Permissions. The local demo permits two send attempts per rolling day. Approval is consumed once; expired or ambiguous checks never sign in.',url:'https://www.twilio.com/docs/verify/api/verification'},
 {name:'Meta WhatsApp updates',status:metaWhatsAppSelected()?`Selected. Booking configuration: ${metaWhatsAppReady('BOOKING')?'present':'missing'}; reminder: ${metaWhatsAppReady('REMINDER')?'present':'missing'}; transaction: ${metaWhatsAppReady('TRANSACTION')?'present':'missing'}`:'Not selected',next:'Approve CareNest Utility templates in the exact configured language. The app checks Meta approval and body variables before sending. Enable WhatsApp preferences on the test account. Acceptance receipts are not delivery receipts.',url:'/account/notifications'},
 {name:'WhatsApp appointment templates',status:`Confirmation: ${fast2smsReady('whatsapp','UPDATE','BOOKING')?'ready':'setup pending'}; ten-minute reminder: ${fast2smsReady('whatsapp','UPDATE','REMINDER')?'ready':'setup pending'}`,next:'Approve separate five-body-variable Utility templates: doctor, date, start/end time in IST, visit type and CareNest link. Keep the worker running for reminders; cancelled, started and obsolete appointments are skipped.',url:'https://docs.fast2sms.com/reference/sendtexttemplate'},
 {name:'SMS OTP mode',status:fast2smsQuickOtp()?'Explicit Quick SMS local demo; maximum two OTP requests per rolling day':'Approved Smart OTP mode',next:'Quick SMS is an explicit local-only choice and not an automatic fallback. Fast2SMS lists it at Rs 5 per SMS; account eligibility and actual phone receipt still need testing. Switch to the approved OTP route for launch.',url:'https://www.fast2sms.com/OTP-SMS-via-API-without-DLT-Registration'},
 {name:'Fast2SMS OTP and updates',status:process.env.FAST2SMS_API_KEY?`Key present. SMS OTP: ${fast2smsReady('sms','OTP')?'ready':'setup pending'}; WhatsApp OTP: ${fast2smsReady('whatsapp','OTP')?'ready':'setup pending'}; SMS updates: ${fast2smsReady('sms','UPDATE')?'ready':'setup pending'}; WhatsApp updates: ${fast2smsReady('whatsapp','UPDATE')?'ready':'setup pending'}`:'Not configured',next:'Approve the messaging templates once and enable delivery. Signup/login OTPs go to the user-entered Indian mobile number; a private test phone restricts optional local update tests only. Spending/resend caps remain; provider acceptance is not proof of handset delivery.',url:'https://docs.fast2sms.com/reference/send-otp'},
 {name:'Human health interoperability',status:'No registered ABDM sandbox or production partner',next:'Apply with the actual organization in the ABDM sandbox; implement against the issued current contract and validate ABDM profiles/consent flows. The local FHIR source export is not ABHA issuance, PM-JAY approval or certification.',url:'https://sandbox.abdm.gov.in/'},
 {name:'Pharmacy, insurer and finance partners',status:'Live partner authority not configured',next:'Use actual licensed pharmacy/pharmacist evidence and reviewed prescribing policy before catalogue publication. Insurance/finance requests remain intake only until approved partners and contracts are supplied.',url:'/admin/clinical'},
 {name:'Company and governance',status:company&&privacy&&clinical&&prescribing?'Operator-entered details and policy attestations recorded; independent evidence required':'Actual company details and/or professional policy approvals missing',next:'Enter the real legal entity, registration, grievance contact and documented professional/legal review. No company, licence or approval is invented.',url:'/admin/governance'}
 ]}
