import React,{useEffect,useState} from 'react'
import {Alert,AppState,SafeAreaView,ScrollView,Text,TextInput,TouchableOpacity,View,StyleSheet} from 'react-native'
import * as Crypto from 'expo-crypto'
import {pair,api,sync} from './src/api'
import {session,enqueue,queue,settle,logout,setOfflineRecords,cacheSnapshot,cachedSnapshot} from './src/storage'
type State={name:string;pets:{id:string;name:string;species:string}[];appointments:{id:string;doctor_name:string;starts_at:string;status:string;revision:number}[];records:{id:string;collection:string;body:Record<string,unknown>}[];slots:{slot_id:string;doctor_id:string;name:string;speciality:string;kind:string;fee_paise:string;slot_start:string}[]}
const date=(s:string)=>new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})
export default function App(){const[code,setCode]=useState(''),[connected,setConnected]=useState(false),[data,setData]=useState<State|null>(null),[tab,setTab]=useState('Home'),[notice,setNotice]=useState(''),[pending,setPending]=useState<Awaited<ReturnType<typeof queue>>>([]),[pet,setPet]=useState<string|null>(null),[busy,setBusy]=useState(false)
 async function run(work:()=>Promise<void>){setBusy(true);try{await work()}catch(e){setNotice(e instanceof Error?e.message:'Try again.')}finally{setBusy(false)}}
 async function refresh(){await sync();const snapshot=await api('/api/mobile/state');setData(snapshot);await cacheSnapshot(snapshot);setPending(await queue());setNotice('Updated from the server. Times shown in IST.')}
 useEffect(()=>{void session().then(s=>{setConnected(Boolean(s));if(s)void run(async()=>{try{await refresh()}catch(e){const cached=await cachedSnapshot();if(cached){setData(cached as unknown as State);setPending(await queue());setNotice('Offline encrypted copy from '+date(String(cached.serverTime))+'. Status and prescriptions may have changed; verify online before acting.')}else throw e}})});const listener=AppState.addEventListener('change',s=>{if(s!=='active')setData(null)});return()=>listener.remove()},[])
 function book(s:State['slots'][number]){Alert.alert('Request appointment',`${s.name} · ${date(s.slot_start)} IST. Share the selected care subject with this clinician. This request needs clinic confirmation.`,[{text:'Back',style:'cancel'},{text:'Consent and request',onPress:()=>void run(async()=>{await enqueue({key:Crypto.randomUUID(),kind:'BOOK',payload:{doctorId:s.doctor_id,slotId:s.slot_id,petId:s.kind==='vet'?pet:null,consent:true}});setPending(await queue());setNotice('Intent saved securely. Reconnect to request the current slot.');try{await refresh()}catch{setNotice('Saved offline. Availability is checked again during sync.')}})}])}
 const button=(label:string,onPress:()=>void,secondary=false)=><TouchableOpacity accessibilityRole="button" disabled={busy} onPress={onPress} style={[styles.button,secondary&&styles.secondary]}><Text style={[styles.buttonText,secondary&&{color:'#0968e8'}]}>{label}</Text></TouchableOpacity>
 if(!connected)return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.logo}>CareNest</Text><Text style={styles.title}>Care for you and your pets</Text><Text style={styles.text}>Create a private pairing code in the website’s Mobile devices page. Use your own account and native build.</Text><TextInput accessibilityLabel="Private pairing code" value={code} onChangeText={setCode} autoCapitalize="none" autoCorrect={false} secureTextEntry style={styles.input}/>{button('Pair this device',()=>void run(async()=>{await pair(code);setCode('');setConnected(true);await refresh()}))}<Text accessibilityLiveRegion="polite" style={styles.text}>{notice}</Text></ScrollView></SafeAreaView>
 return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.content}><Text style={styles.logo}>CareNest</Text><Text style={styles.title}>{tab==='Home'?`Hello, ${data?.name??'there'}`:tab}</Text>{button('Refresh and sync',()=>void run(refresh),true)}<Text accessibilityLiveRegion="polite" style={styles.text}>{notice}</Text>{!data&&<Text style={styles.text}>Refresh while online to view care records. Signed records are kept in memory and hidden when the app leaves the foreground.</Text>}
 {tab==='Home'&&data?.appointments.map(a=><View style={styles.card} key={a.id}><Text style={styles.heading}>{a.doctor_name}</Text><Text style={styles.text}>{a.status} · {date(a.starts_at)} IST</Text>{['requested','confirmed'].includes(a.status)&&button('Request cancellation',()=>Alert.alert('Cancel appointment','The server must accept the current revision.',[{text:'Back'},{text:'Cancel appointment',onPress:()=>void run(async()=>{await enqueue({key:Crypto.randomUUID(),kind:'CANCEL',payload:{bookingId:a.id,revision:a.revision}});await refresh()})}]),true)}</View>)}
 {tab==='Find care'&&<><View style={styles.card}><Text style={styles.heading}>Care subject</Text>{button('Human care',()=>setPet(null),true)}{data?.pets.map(p=><View key={p.id}>{button(`${pet===p.id?'Selected: ':''}${p.name} · ${p.species}`,()=>setPet(p.id),true)}</View>)}</View>{data?.slots.filter(s=>pet?s.kind==='vet':s.kind==='human').map(s=><View style={styles.card} key={s.slot_id}><Text style={styles.heading}>{s.name}</Text><Text style={styles.text}>{s.speciality} · ₹{Number(s.fee_paise)/100}</Text><Text style={styles.text}>{date(s.slot_start)} IST</Text>{button('Request appointment',()=>book(s))}</View>)}</>}
 {tab==='Records'&&data?.records.map(r=><View style={styles.card} key={r.id}><Text style={styles.heading}>{r.collection==='prescriptions'?'Prescription':'Clinical note'} · {String(r.body.patientName??'')}</Text><Text style={styles.text}>{JSON.stringify(r.body,null,2)}</Text></View>)}
 {tab==='Pets'&&data?.pets.map(p=><View style={styles.card} key={p.id}><Text style={styles.heading}>{p.name}</Text><Text style={styles.text}>{p.species}</Text></View>)}
 {tab==='Account'&&<>{button('Enable encrypted offline records for 24 hours',()=>Alert.alert('Keep your own care records on this device','Save an encrypted copy on your own locked device for at most 24 hours. Cached prescriptions and appointment status can change. Offline data cannot be remotely cleared until the device reconnects.',[{text:'Back',style:'cancel'},{text:'Enable my private copy',onPress:()=>void run(async()=>{await setOfflineRecords(true);await refresh()})}]),true)}{button('Disable and remove cached records',()=>void run(async()=>{await setOfflineRecords(false);setNotice('Offline record copies removed.')}),true)}{button('Read my valid offline copy',()=>void run(async()=>{const cached=await cachedSnapshot();if(!cached)throw new Error('No unexpired opted-in offline copy is available.');setData(cached as unknown as State);setNotice('Encrypted cached copy from '+date(String(cached.serverTime))+'. Verify current status online.')}),true)}{button('Sign out and clear local data',()=>void run(async()=>{await logout();setConnected(false);setData(null);setPending([]);setNotice('Local session and pending data cleared.')}),true)}<Text style={styles.heading}>Encrypted pending requests</Text>{pending.map(i=><View style={styles.card} key={i.key}><Text>{i.kind} · {i.error??'Waiting for sync'}</Text>{button('Discard pending request',()=>void run(async()=>{await settle(i.key);setPending(await queue())}),true)}</View>)}</>}
 </ScrollView><View style={styles.nav}>{['Home','Find care','Records','Pets','Account'].map(t=><TouchableOpacity key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>setTab(t)} style={styles.navItem}><Text style={{color:tab===t?'#0968e8':'#64748b',fontSize:11,fontWeight:'600'}}>{t}</Text></TouchableOpacity>)}</View></SafeAreaView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#f5f9ff'},content:{padding:20,paddingBottom:36},logo:{fontSize:18,color:'#0968e8',fontWeight:'800',marginBottom:24},title:{fontSize:28,fontWeight:'700',color:'#102038',marginBottom:18},text:{fontSize:14,color:'#485970',lineHeight:22,marginVertical:8},heading:{fontSize:18,fontWeight:'700',color:'#102038'},card:{backgroundColor:'white',borderRadius:22,padding:18,marginTop:18,borderWidth:1,borderColor:'#e5edf8'},input:{backgroundColor:'white',minHeight:48,borderRadius:16,borderWidth:1,borderColor:'#c4d9f5',padding:14,marginVertical:20},button:{backgroundColor:'#0875f5',borderRadius:16,minHeight:48,justifyContent:'center',alignItems:'center',padding:12,marginTop:12},secondary:{backgroundColor:'#eaf2ff'},buttonText:{color:'white',fontWeight:'700'},nav:{flexDirection:'row',backgroundColor:'white',borderTopWidth:1,borderColor:'#e5edf8',paddingBottom:10},navItem:{flex:1,minHeight:52,alignItems:'center',justifyContent:'center'}})
