import Link from 'next/link'
import {requireRole} from '@/lib/auth'
import {getDb,ensureSchema} from '@/lib/db/client'
import {integrationConfigured} from '@/lib/domain/video'
import {livekitConfigured} from '@/lib/domain/livekit'
import {selectVideoProvider} from '@/app/actions/video'
export const dynamic='force-dynamic'
export default async function IntegrationsPage(){
 const u=await requireRole('doctor','/practice/integrations');await ensureSchema()
 const connection=await getDb().one("SELECT id FROM provider.connections WHERE user_id=$1 AND provider='google' AND revoked_at IS NULL",[u.id]),d=await getDb().one<{video_provider:string}>('SELECT video_provider FROM provider.doctors WHERE user_id=$1',[u.id])
 return <div className="space-y-6"><h1 className="text-3xl">Consultation integrations</h1><p>Current video service: {d?.video_provider==='google'?'Google Meet':'LiveKit'}. Complete pending video appointments before changing services.</p><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-card p-6"><h2 className="text-2xl">LiveKit in-app calls</h2><p className="my-4">{livekitConfigured()?'Local video credentials are configured. No personal video account is needed.':'The administrator needs to set up the local video service.'}</p>{livekitConfigured()&&<form action={selectVideoProvider}><input type="hidden" name="provider" value="livekit"/><button className="care-button">Use LiveKit for new video appointments</button></form>}<p className="mt-4 text-sm">Patient and clinician access is checked for each appointment. Camera and microphone start off; recording, chat and screen sharing are disabled.</p></section><section className="rounded-2xl border bg-card p-6"><h2 className="text-2xl">Google Meet & Calendar</h2><p className="my-4">{connection?'Your Google account is connected.':integrationConfigured('google')?'Connect your clinician Google account.':'Google application credentials are still needed.'}</p>{integrationConfigured('google')&&<Link href="/api/integrations/google/connect" className="care-button">{connection?'Reconnect Google':'Connect Google'}</Link>}{connection&&<form className="mt-4" action={selectVideoProvider}><input type="hidden" name="provider" value="google"/><button className="care-button">Use Google Meet for new video appointments</button></form>}<p className="mt-4 text-sm">Google Meet opens through a participant-scoped link. Calendar conference creation is reconciled by the worker.</p></section></div></div>
}
