import Link from 'next/link'
import {requireUser} from '@/lib/auth'
import {patientAppointments} from '@/lib/domain/patient'
import {ownedPets} from '@/lib/domain/pets'
import {listFamily} from '@/lib/db/family'
import {PatientWorkspace} from '@/components/patient-workspace'
import {slotDay,slotTime} from '@/lib/slot-format'
export const dynamic='force-dynamic'
export default async function PatientDashboard(){const user=await requireUser('/dashboard/patient');const [appointments,pets,family]=await Promise.all([patientAppointments(user.id),ownedPets(user.id),listFamily(user.id)]);const next=appointments.upcoming[0];return <PatientWorkspace title={`Your care, ${user.name||'welcome'}`}><div className="grid gap-5 md:grid-cols-3">{[['Upcoming visits',appointments.upcoming.length,'/account'],['Household members',family.length,'/account/profile'],['Pets',pets.length,'/account/pets']].map(([label,count,href])=><Link key={String(label)} href={String(href)} className="rounded-2xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-bold text-primary">{count}</p></Link>)}</div><section className="appointment-banner mt-7"><p className="text-xs">Next appointment</p><h2 className="mt-3 text-xl">{next?next.doctor_name:'Find your next step'}</h2><p className="mt-3 text-sm">{next?.starts_at?`${slotDay(next.starts_at)}, ${slotTime(next.starts_at)} · ${next.status}`:'Choose a doctor or veterinarian and request a suitable time.'}</p><Link href={next?'/account':'/search'} className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-white px-4 text-sm font-semibold text-[#075ac9]">{next?'View appointment':'Find care'}</Link></section><div className="mt-7 grid gap-4 sm:grid-cols-2"><Link href="/account/records" className="rounded-2xl border border-border bg-card p-6">Consultation notes and prescriptions</Link><Link href="/account/labs" className="rounded-2xl border border-border bg-card p-6">Lab orders and results</Link><Link href="/account/notifications" className="rounded-2xl border border-border bg-card p-6">Appointment updates</Link><Link href="/surgeries" className="rounded-2xl border border-border bg-card p-6">Surgery enquiries</Link></div></PatientWorkspace>}
