import {requireUser,newId} from '@/lib/auth'
import {PatientWorkspace} from '@/components/patient-workspace'
import {ownMedicineOrders,pharmacyCatalogue} from '@/lib/domain/pharmacy'
import {patientRecords} from '@/lib/domain/clinical'
import {ownAddresses} from '@/lib/domain/home-visits'
import {MedicineOrderForm} from '@/components/pharmacy-forms'
import {decimalRupees} from '@/lib/money'
export const dynamic='force-dynamic'
export default async function PharmacyAccount(){const u=await requireUser('/account/pharmacy'),orders=await ownMedicineOrders(u.id),items=await pharmacyCatalogue(),prescriptions=(await patientRecords(u.id)).filter(r=>r.collection==='prescriptions').map(r=>({id:r.id,name:String(r.body.patientName)+' · '+r.created_at.slice(0,10)})),addresses=(await ownAddresses(u.id)).map(a=>({id:a.id,name:a.label}));return <PatientWorkspace title="Prescription requests" description="Request pharmacist review against your current signed prescription. Human and pet medicines require reviewed species support."><section className="space-y-4"><h2 className="text-xl">Your requests</h2>{orders.map(o=><article key={o.id} className="rounded-2xl border p-5"><p>{o.partner_name} · {o.state} · ₹{decimalRupees(o.total_paise)}</p></article>)}<a href="/account/billing" className="inline-flex min-h-11 items-center text-primary">Invoices and actual receipts</a></section><section className="mt-6 grid gap-5 md:grid-cols-2">{items.map(i=><article key={i.partner_id+':'+i.id} className="rounded-2xl border p-5"><h2 className="text-xl">{i.name} · {i.strength}</h2><p className="mt-2">{i.partner_name} · {i.form} · ₹{decimalRupees(i.price_paise)} per unit · {i.available} available</p><MedicineOrderForm item={i} prescriptions={prescriptions} addresses={addresses} requestKey={newId('medicine-request')}/></article>)}{!items.length&&<p className="rounded-2xl border border-dashed p-6">A verified pharmacy and professionally reviewed catalogue must be configured before requests are available.</p>}</section></PatientWorkspace>}
