import Link from 'next/link'
import {currentUser,newId} from '@/lib/auth'
import {labPackages} from '@/lib/domain/labs'
import {listFamily} from '@/lib/db/family'
import {SiteHeader} from '@/components/site-header'
import {SiteFooter} from '@/components/site-footer'
import {LabRequestForm} from '@/components/lab-order-forms'
import {formatPaise} from '@/lib/money'
export const dynamic='force-dynamic'
export default async function LabsPage(){const user=await currentUser(),packages=await labPackages(),family=user?await listFamily(user.id):[];return <main className="min-h-screen bg-background"><SiteHeader/><div className="care-container py-10"><h1 className="text-3xl sm:text-5xl">Laboratory requests</h1><p className="mt-4 max-w-xl text-sm leading-7 text-muted-foreground">Request a published package. The assigned lab confirms collection and attaches actual results.</p><Link href="/account/labs" className="care-button mt-5">Your lab orders</Link><div className="mt-7 grid gap-5 lg:grid-cols-2">{packages.map(p=><article key={p.id} className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl">{p.name}</h2>{p.is_demo&&<p className="mt-2 text-xs font-semibold text-warning">Sample workflow; no real collection or testing is supplied</p>}<p className="mt-3 text-sm text-muted-foreground">{p.description}</p><p className="mt-3 text-sm">{p.clinic_name} · {p.address}</p><p className="mt-4 text-xl font-bold text-primary">{formatPaise(p.fee_paise)}</p>{user?<LabRequestForm packageId={p.id} requestKey={newId('lab-request')} family={family}/>:<Link className="care-button mt-4" href="/sign-in?next=%2Flabs">Sign in to request</Link>}</article>)}</div>{!packages.length&&<p className="mt-6 rounded-2xl border border-dashed border-border p-7 text-sm">No verified lab packages are currently published. No test, collection or turnaround service is promised by this empty catalogue.</p>}</div><SiteFooter/></main>}
